<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Authentication;

use LoyaltyApIsLib\Models\OAuthToken;

/**
 * Interface for defining the behavior of Authentication.
 */
interface ClientAuthorizationTokenCredentials
{
    /**
     * String value for oauthClientId.
     */
    public function getOauthClientId(): string;

    /**
     * String value for oauthClientSecret.
     */
    public function getOauthClientSecret(): string;

    /**
     * OauthToken value for oauthToken.
     */
    public function getOauthToken(): ?OauthToken;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $oauthClientId OAuth 2 Client ID
     * @param string $oauthClientSecret OAuth 2 Client Secret
     */
    public function equals(string $oauthClientId, string $oauthClientSecret): bool;

    /**
     * Fetch the OAuth token.
     *
     * @param array|null $additionalParams Additional parameters to be sent.
     */
    public function fetchToken(?array $additionalParams = null): OAuthToken;

    /**
     * Has the OAuth token expired? If the token argument is not provided then this function will check the
     * expiry of the initial oauthToken, that's set in the client initialization.
     */
    public function isTokenExpired(?OAuthToken $token = null): bool;
}
