<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing CustomerHeader security credentials.
 */
class CustomerHeaderCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for CustomerHeaderCredentialsBuilder
     *
     * @param string $authorizationToken
     */
    public static function init(string $authorizationToken): self
    {
        return new self(['authorizationToken' => $authorizationToken]);
    }

    /**
     * Setter for AuthorizationToken.
     *
     * @param string $authorizationToken
     *
     * @return $this
     */
    public function authorizationToken(string $authorizationToken): self
    {
        $this->config['authorizationToken'] = $authorizationToken;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
