<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Authentication;

use Core\Authentication\CoreAuth;
use LoyaltyApIsLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class CustomerHeaderManager extends CoreAuth implements CustomerHeaderCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(
            HeaderParam::init('Authorization-Token', $this->getAuthorizationToken())->requiredNonEmpty()
        );
    }

    /**
     * String value for authorizationToken.
     */
    public function getAuthorizationToken(): string
    {
        return $this->config['authorizationToken'] ?? ConfigurationDefaults::AUTHORIZATION_TOKEN;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorizationToken The partner's API key
     */
    public function equals(string $authorizationToken): bool
    {
        return $authorizationToken == $this->getAuthorizationToken();
    }
}
