<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface CustomerHeaderCredentials
{
    /**
     * String value for authorizationToken.
     */
    public function getAuthorizationToken(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorizationToken The partner's API key
     */
    public function equals(string $authorizationToken): bool;
}
