<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Authentication;

use Core\Authentication\CoreAuth;
use LoyaltyApIsLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class PublicBasicTokenManager extends CoreAuth implements PublicBasicTokenCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(
            HeaderParam::init('Public Basic Token', $this->getPublicBasicToken())->requiredNonEmpty()
        );
    }

    /**
     * String value for publicBasicToken.
     */
    public function getPublicBasicToken(): string
    {
        return $this->config['publicBasicToken'] ?? ConfigurationDefaults::PUBLIC_BASIC_TOKEN;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $publicBasicToken
     */
    public function equals(string $publicBasicToken): bool
    {
        return $publicBasicToken == $this->getPublicBasicToken();
    }
}
