<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Authentication;

/**
 * Interface for defining the behavior of Authentication.
 */
interface PublicBasicTokenCredentials
{
    /**
     * String value for publicBasicToken.
     */
    public function getPublicBasicToken(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $publicBasicToken
     */
    public function equals(string $publicBasicToken): bool;
}
