<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing PublicBasicToken security credentials.
 */
class PublicBasicTokenCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for PublicBasicTokenCredentialsBuilder
     *
     * @param string $publicBasicToken
     */
    public static function init(string $publicBasicToken): self
    {
        return new self(['publicBasicToken' => $publicBasicToken]);
    }

    /**
     * Setter for PublicBasicToken.
     *
     * @param string $publicBasicToken
     *
     * @return $this
     */
    public function publicBasicToken(string $publicBasicToken): self
    {
        $this->config['publicBasicToken'] = $publicBasicToken;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
