<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\AccessCodeResponse;

/**
 * Builder for model AccessCodeResponse
 *
 * @see AccessCodeResponse
 */
class AccessCodeResponseBuilder
{
    /**
     * @var AccessCodeResponse
     */
    private $instance;

    private function __construct(AccessCodeResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Access Code Response Builder object.
     */
    public static function init(): self
    {
        return new self(new AccessCodeResponse());
    }

    /**
     * Sets access Code field.
     *
     * @param string|null $value
     */
    public function accessCode(?string $value): self
    {
        $this->instance->setAccessCode($value);
        return $this;
    }

    /**
     * Sets expires In field.
     *
     * @param int|null $value
     */
    public function expiresIn(?int $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Access Code Response object.
     */
    public function build(): AccessCodeResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
