<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\AuthTokenRequest;

/**
 * Builder for model AuthTokenRequest
 *
 * @see AuthTokenRequest
 */
class AuthTokenRequestBuilder
{
    /**
     * @var AuthTokenRequest
     */
    private $instance;

    private function __construct(AuthTokenRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Auth Token Request Builder object.
     */
    public static function init(): self
    {
        return new self(new AuthTokenRequest());
    }

    /**
     * Sets digest field.
     *
     * @param string|null $value
     */
    public function digest(?string $value): self
    {
        $this->instance->setDigest($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Auth Token Request object.
     */
    public function build(): AuthTokenRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
