<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\AuthTokenResponse;

/**
 * Builder for model AuthTokenResponse
 *
 * @see AuthTokenResponse
 */
class AuthTokenResponseBuilder
{
    /**
     * @var AuthTokenResponse
     */
    private $instance;

    private function __construct(AuthTokenResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Auth Token Response Builder object.
     */
    public static function init(): self
    {
        return new self(new AuthTokenResponse());
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets token Type field.
     *
     * @param string|null $value
     */
    public function tokenType(?string $value): self
    {
        $this->instance->setTokenType($value);
        return $this;
    }

    /**
     * Sets expires In field.
     *
     * @param string|null $value
     */
    public function expiresIn(?string $value): self
    {
        $this->instance->setExpiresIn($value);
        return $this;
    }

    /**
     * Sets owner field.
     *
     * @param string|null $value
     */
    public function owner(?string $value): self
    {
        $this->instance->setOwner($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Auth Token Response object.
     */
    public function build(): AuthTokenResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
