<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\BadRequestError;
use LoyaltyApIsLib\Models\Fault;

/**
 * Builder for model BadRequestError
 *
 * @see BadRequestError
 */
class BadRequestErrorBuilder
{
    /**
     * @var BadRequestError
     */
    private $instance;

    private function __construct(BadRequestError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bad Request Error Builder object.
     */
    public static function init(): self
    {
        return new self(new BadRequestError());
    }

    /**
     * Sets fault field.
     *
     * @param Fault|null $value
     */
    public function fault(?Fault $value): self
    {
        $this->instance->setFault($value);
        return $this;
    }

    /**
     * Initializes a new Bad Request Error object.
     */
    public function build(): BadRequestError
    {
        return CoreHelper::clone($this->instance);
    }
}
