<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\BalanceAmount;
use LoyaltyApIsLib\Models\BalanceCurrencyAmount;

/**
 * Builder for model BalanceAmount
 *
 * @see BalanceAmount
 */
class BalanceAmountBuilder
{
    /**
     * @var BalanceAmount
     */
    private $instance;

    private function __construct(BalanceAmount $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Balance Amount Builder object.
     */
    public static function init(): self
    {
        return new self(new BalanceAmount());
    }

    /**
     * Sets amounts field.
     *
     * @param BalanceCurrencyAmount[]|null $value
     */
    public function amounts(?array $value): self
    {
        $this->instance->setAmounts($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Balance Amount object.
     */
    public function build(): BalanceAmount
    {
        return CoreHelper::clone($this->instance);
    }
}
