<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\BalanceAmountDetail;
use LoyaltyApIsLib\Models\BalanceCurrencyAmount;

/**
 * Builder for model BalanceCurrencyAmount
 *
 * @see BalanceCurrencyAmount
 */
class BalanceCurrencyAmountBuilder
{
    /**
     * @var BalanceCurrencyAmount
     */
    private $instance;

    private function __construct(BalanceCurrencyAmount $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Balance Currency Amount Builder object.
     *
     * @param string $currencyType
     */
    public static function init(string $currencyType): self
    {
        return new self(new BalanceCurrencyAmount($currencyType));
    }

    /**
     * Sets amounts field.
     *
     * @param BalanceAmountDetail[]|null $value
     */
    public function amounts(?array $value): self
    {
        $this->instance->setAmounts($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Balance Currency Amount object.
     */
    public function build(): BalanceCurrencyAmount
    {
        return CoreHelper::clone($this->instance);
    }
}
