<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\BalanceAmountDetail;

/**
 * Builder for model BalanceAmountDetail
 *
 * @see BalanceAmountDetail
 */
class BalanceAmountDetailBuilder
{
    /**
     * @var BalanceAmountDetail
     */
    private $instance;

    private function __construct(BalanceAmountDetail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Balance Amount Detail Builder object.
     *
     * @param float $amount
     * @param string $state
     * @param \DateTime $dateTime
     * @param int $dateTimestamp
     */
    public static function init(float $amount, string $state, \DateTime $dateTime, int $dateTimestamp): self
    {
        return new self(new BalanceAmountDetail($amount, $state, $dateTime, $dateTimestamp));
    }

    /**
     * Sets cash Amount field.
     *
     * @param float|null $value
     */
    public function cashAmount(?float $value): self
    {
        $this->instance->setCashAmount($value);
        return $this;
    }

    /**
     * Sets period field.
     *
     * @param int|null $value
     */
    public function period(?int $value): self
    {
        $this->instance->setPeriod($value);
        return $this;
    }

    /**
     * Sets position field.
     *
     * @param int[]|null $value
     */
    public function position(?array $value): self
    {
        $this->instance->setPosition($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Balance Amount Detail object.
     */
    public function build(): BalanceAmountDetail
    {
        return CoreHelper::clone($this->instance);
    }
}
