<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\ClientAuthTokenRequest;

/**
 * Builder for model ClientAuthTokenRequest
 *
 * @see ClientAuthTokenRequest
 */
class ClientAuthTokenRequestBuilder
{
    /**
     * @var ClientAuthTokenRequest
     */
    private $instance;

    private function __construct(ClientAuthTokenRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Client Auth Token Request Builder object.
     *
     * @param string $clientId
     * @param string $clientSecret
     * @param string $grantType
     */
    public static function init(string $clientId, string $clientSecret, string $grantType): self
    {
        return new self(new ClientAuthTokenRequest($clientId, $clientSecret, $grantType));
    }

    /**
     * Initializes a new Client Auth Token Request object.
     */
    public function build(): ClientAuthTokenRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
