<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\CurrencyData;

/**
 * Builder for model CurrencyData
 *
 * @see CurrencyData
 */
class CurrencyDataBuilder
{
    /**
     * @var CurrencyData
     */
    private $instance;

    private function __construct(CurrencyData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Currency Data Builder object.
     *
     * @param string $code
     * @param string $symbol
     * @param bool $isSuffix
     * @param bool $hasSpace
     */
    public static function init(string $code, string $symbol, bool $isSuffix, bool $hasSpace): self
    {
        return new self(new CurrencyData($code, $symbol, $isSuffix, $hasSpace));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Currency Data object.
     */
    public function build(): CurrencyData
    {
        return CoreHelper::clone($this->instance);
    }
}
