<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\BalanceAmount;
use LoyaltyApIsLib\Models\CustomerBalances;

/**
 * Builder for model CustomerBalances
 *
 * @see CustomerBalances
 */
class CustomerBalancesBuilder
{
    /**
     * @var CustomerBalances
     */
    private $instance;

    private function __construct(CustomerBalances $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Customer Balances Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomerBalances());
    }

    /**
     * Sets balances field.
     *
     * @param BalanceAmount[]|null $value
     */
    public function balances(?array $value): self
    {
        $this->instance->setBalances($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Customer Balances object.
     */
    public function build(): CustomerBalances
    {
        return CoreHelper::clone($this->instance);
    }
}
