<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\ErrorBaseContainer;
use LoyaltyApIsLib\Models\ErrorPresenter;

/**
 * Builder for model ErrorBaseContainer
 *
 * @see ErrorBaseContainer
 */
class ErrorBaseContainerBuilder
{
    /**
     * @var ErrorBaseContainer
     */
    private $instance;

    private function __construct(ErrorBaseContainer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Base Container Builder object.
     *
     * @param ErrorPresenter $user
     * @param ErrorPresenter $developer
     */
    public static function init(ErrorPresenter $user, ErrorPresenter $developer): self
    {
        return new self(new ErrorBaseContainer($user, $developer));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Base Container object.
     */
    public function build(): ErrorBaseContainer
    {
        return CoreHelper::clone($this->instance);
    }
}
