<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\ErrorInfo;
use LoyaltyApIsLib\Models\ErrorPresenter;

/**
 * Builder for model ErrorInfo
 *
 * @see ErrorInfo
 */
class ErrorInfoBuilder
{
    /**
     * @var ErrorInfo
     */
    private $instance;

    private function __construct(ErrorInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Info Builder object.
     *
     * @param ErrorPresenter $user
     */
    public static function init(ErrorPresenter $user): self
    {
        return new self(new ErrorInfo($user));
    }

    /**
     * Sets Developer field.
     *
     * @param ErrorPresenter|null $value
     */
    public function developer(?ErrorPresenter $value): self
    {
        $this->instance->setDeveloper($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Info object.
     */
    public function build(): ErrorInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
