<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\ErrorItem;
use LoyaltyApIsLib\Models\ErrorSource;

/**
 * Builder for model ErrorItem
 *
 * @see ErrorItem
 */
class ErrorItemBuilder
{
    /**
     * @var ErrorItem
     */
    private $instance;

    private function __construct(ErrorItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Item Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorItem());
    }

    /**
     * Sets status field.
     *
     * @param int|null $value
     */
    public function status(?int $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Sets source field.
     *
     * @param ErrorSource|null $value
     */
    public function source(?ErrorSource $value): self
    {
        $this->instance->setSource($value);
        return $this;
    }

    /**
     * Sets detail field.
     *
     * @param string|null $value
     */
    public function detail(?string $value): self
    {
        $this->instance->setDetail($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Item object.
     */
    public function build(): ErrorItem
    {
        return CoreHelper::clone($this->instance);
    }
}
