<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\ErrorSource;

/**
 * Builder for model ErrorSource
 *
 * @see ErrorSource
 */
class ErrorSourceBuilder
{
    /**
     * @var ErrorSource
     */
    private $instance;

    private function __construct(ErrorSource $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Source Builder object.
     */
    public static function init(): self
    {
        return new self(new ErrorSource());
    }

    /**
     * Sets pointer field.
     *
     * @param string|null $value
     */
    public function pointer(?string $value): self
    {
        $this->instance->setPointer($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Source object.
     */
    public function build(): ErrorSource
    {
        return CoreHelper::clone($this->instance);
    }
}
