<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\ErrorPresenter;

/**
 * Builder for model ErrorPresenter
 *
 * @see ErrorPresenter
 */
class ErrorPresenterBuilder
{
    /**
     * @var ErrorPresenter
     */
    private $instance;

    private function __construct(ErrorPresenter $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Presenter Builder object.
     *
     * @param string $appErrorCode
     * @param string $message
     */
    public static function init(string $appErrorCode, string $message): self
    {
        return new self(new ErrorPresenter($appErrorCode, $message));
    }

    /**
     * Sets reason field.
     *
     * @param string|null $value
     */
    public function reason(?string $value): self
    {
        $this->instance->setReason($value);
        return $this;
    }

    /**
     * Unsets reason field.
     */
    public function unsetReason(): self
    {
        $this->instance->unsetReason();
        return $this;
    }

    /**
     * Sets subject field.
     *
     * @param string|null $value
     */
    public function subject(?string $value): self
    {
        $this->instance->setSubject($value);
        return $this;
    }

    /**
     * Unsets subject field.
     */
    public function unsetSubject(): self
    {
        $this->instance->unsetSubject();
        return $this;
    }

    /**
     * Sets subject Type field.
     *
     * @param string|null $value
     */
    public function subjectType(?string $value): self
    {
        $this->instance->setSubjectType($value);
        return $this;
    }

    /**
     * Unsets subject Type field.
     */
    public function unsetSubjectType(): self
    {
        $this->instance->unsetSubjectType();
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Unsets type field.
     */
    public function unsetType(): self
    {
        $this->instance->unsetType();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Error Presenter object.
     */
    public function build(): ErrorPresenter
    {
        return CoreHelper::clone($this->instance);
    }
}
