<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\EvChargingDetails;

/**
 * Builder for model EvChargingDetails
 *
 * @see EvChargingDetails
 */
class EvChargingDetailsBuilder
{
    /**
     * @var EvChargingDetails
     */
    private $instance;

    private function __construct(EvChargingDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Ev Charging Details Builder object.
     *
     * @param string $chargePointSerialId
     * @param \DateTime $startDateTime
     * @param \DateTime $endDateTime
     * @param int $duration
     */
    public static function init(
        string $chargePointSerialId,
        \DateTime $startDateTime,
        \DateTime $endDateTime,
        int $duration
    ): self {
        return new self(new EvChargingDetails($chargePointSerialId, $startDateTime, $endDateTime, $duration));
    }

    /**
     * Sets charge Point Connector Type Cd field.
     *
     * @param string|null $value
     */
    public function chargePointConnectorTypeCd(?string $value): self
    {
        $this->instance->setChargePointConnectorTypeCd($value);
        return $this;
    }

    /**
     * Sets charge Point Connector Type Desc field.
     *
     * @param string|null $value
     */
    public function chargePointConnectorTypeDesc(?string $value): self
    {
        $this->instance->setChargePointConnectorTypeDesc($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Ev Charging Details object.
     */
    public function build(): EvChargingDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
