<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\ExchangeAccessCodeRequest;

/**
 * Builder for model ExchangeAccessCodeRequest
 *
 * @see ExchangeAccessCodeRequest
 */
class ExchangeAccessCodeRequestBuilder
{
    /**
     * @var ExchangeAccessCodeRequest
     */
    private $instance;

    private function __construct(ExchangeAccessCodeRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Exchange Access Code Request Builder object.
     */
    public static function init(): self
    {
        return new self(new ExchangeAccessCodeRequest());
    }

    /**
     * Sets access Code field.
     *
     * @param string|null $value
     */
    public function accessCode(?string $value): self
    {
        $this->instance->setAccessCode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Exchange Access Code Request object.
     */
    public function build(): ExchangeAccessCodeRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
