<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\FaultDetail;

/**
 * Builder for model FaultDetail
 *
 * @see FaultDetail
 */
class FaultDetailBuilder
{
    /**
     * @var FaultDetail
     */
    private $instance;

    private function __construct(FaultDetail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fault Detail Builder object.
     */
    public static function init(): self
    {
        return new self(new FaultDetail());
    }

    /**
     * Sets errorcode field.
     *
     * @param string|null $value
     */
    public function errorcode(?string $value): self
    {
        $this->instance->setErrorcode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Fault Detail object.
     */
    public function build(): FaultDetail
    {
        return CoreHelper::clone($this->instance);
    }
}
