<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\Fault;
use LoyaltyApIsLib\Models\FaultDetail;

/**
 * Builder for model Fault
 *
 * @see Fault
 */
class FaultBuilder
{
    /**
     * @var Fault
     */
    private $instance;

    private function __construct(Fault $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fault Builder object.
     */
    public static function init(): self
    {
        return new self(new Fault());
    }

    /**
     * Sets faultstring field.
     *
     * @param string|null $value
     */
    public function faultstring(?string $value): self
    {
        $this->instance->setFaultstring($value);
        return $this;
    }

    /**
     * Sets detail field.
     *
     * @param FaultDetail|null $value
     */
    public function detail(?FaultDetail $value): self
    {
        $this->instance->setDetail($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Fault object.
     */
    public function build(): Fault
    {
        return CoreHelper::clone($this->instance);
    }
}
