<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\JsonApiVersion;

/**
 * Builder for model JsonApiVersion
 *
 * @see JsonApiVersion
 */
class JsonApiVersionBuilder
{
    /**
     * @var JsonApiVersion
     */
    private $instance;

    private function __construct(JsonApiVersion $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Json Api Version Builder object.
     */
    public static function init(): self
    {
        return new self(new JsonApiVersion());
    }

    /**
     * Sets version field.
     *
     * @param string|null $value
     */
    public function version(?string $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Json Api Version object.
     */
    public function build(): JsonApiVersion
    {
        return CoreHelper::clone($this->instance);
    }
}
