<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\LoyaltyCardInfo;

/**
 * Builder for model LoyaltyCardInfo
 *
 * @see LoyaltyCardInfo
 */
class LoyaltyCardInfoBuilder
{
    /**
     * @var LoyaltyCardInfo
     */
    private $instance;

    private function __construct(LoyaltyCardInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Loyalty Card Info Builder object.
     */
    public static function init(): self
    {
        return new self(new LoyaltyCardInfo());
    }

    /**
     * Sets loyalty Card field.
     *
     * @param string|null $value
     */
    public function loyaltyCard(?string $value): self
    {
        $this->instance->setLoyaltyCard($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Loyalty Card Info object.
     */
    public function build(): LoyaltyCardInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
