<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\M200UserPartners;

/**
 * Builder for model M200UserPartners
 *
 * @see M200UserPartners
 */
class M200UserPartnersBuilder
{
    /**
     * @var M200UserPartners
     */
    private $instance;

    private function __construct(M200UserPartners $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new M200 User Partners Builder object.
     *
     * @param string $uuid
     * @param string $userStatus
     * @param array $market
     * @param string $accessToken
     * @param string $refreshToken
     */
    public static function init(
        string $uuid,
        string $userStatus,
        array $market,
        string $accessToken,
        string $refreshToken
    ): self {
        return new self(new M200UserPartners($uuid, $userStatus, $market, $accessToken, $refreshToken));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new M200 User Partners object.
     */
    public function build(): M200UserPartners
    {
        return CoreHelper::clone($this->instance);
    }
}
