<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\Fault;
use LoyaltyApIsLib\Models\MethodNotAllowedError;

/**
 * Builder for model MethodNotAllowedError
 *
 * @see MethodNotAllowedError
 */
class MethodNotAllowedErrorBuilder
{
    /**
     * @var MethodNotAllowedError
     */
    private $instance;

    private function __construct(MethodNotAllowedError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Method Not Allowed Error Builder object.
     */
    public static function init(): self
    {
        return new self(new MethodNotAllowedError());
    }

    /**
     * Sets fault field.
     *
     * @param Fault|null $value
     */
    public function fault(?Fault $value): self
    {
        $this->instance->setFault($value);
        return $this;
    }

    /**
     * Initializes a new Method Not Allowed Error object.
     */
    public function build(): MethodNotAllowedError
    {
        return CoreHelper::clone($this->instance);
    }
}
