<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\Fault;
use LoyaltyApIsLib\Models\NotFoundError;

/**
 * Builder for model NotFoundError
 *
 * @see NotFoundError
 */
class NotFoundErrorBuilder
{
    /**
     * @var NotFoundError
     */
    private $instance;

    private function __construct(NotFoundError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Not Found Error Builder object.
     */
    public static function init(): self
    {
        return new self(new NotFoundError());
    }

    /**
     * Sets fault field.
     *
     * @param Fault|null $value
     */
    public function fault(?Fault $value): self
    {
        $this->instance->setFault($value);
        return $this;
    }

    /**
     * Initializes a new Not Found Error object.
     */
    public function build(): NotFoundError
    {
        return CoreHelper::clone($this->instance);
    }
}
