<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\Offer;

/**
 * Builder for model Offer
 *
 * @see Offer
 */
class OfferBuilder
{
    /**
     * @var Offer
     */
    private $instance;

    private function __construct(Offer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offer Builder object.
     *
     * @param int $offerId
     * @param string $referenceId
     * @param string $title
     * @param string $description
     * @param \DateTime $validFrom
     */
    public static function init(
        int $offerId,
        string $referenceId,
        string $title,
        string $description,
        \DateTime $validFrom
    ): self {
        return new self(new Offer($offerId, $referenceId, $title, $description, $validFrom));
    }

    /**
     * Sets valid To field.
     *
     * @param \DateTime|null $value
     */
    public function validTo(?\DateTime $value): self
    {
        $this->instance->setValidTo($value);
        return $this;
    }

    /**
     * Unsets valid To field.
     */
    public function unsetValidTo(): self
    {
        $this->instance->unsetValidTo();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Offer object.
     */
    public function build(): Offer
    {
        return CoreHelper::clone($this->instance);
    }
}
