<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\OfferInfo;

/**
 * Builder for model OfferInfo
 *
 * @see OfferInfo
 */
class OfferInfoBuilder
{
    /**
     * @var OfferInfo
     */
    private $instance;

    private function __construct(OfferInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offer Info Builder object.
     *
     * @param float $discountValue
     * @param string $loyaltyOfferId
     * @param string $reason
     */
    public static function init(float $discountValue, string $loyaltyOfferId, string $reason): self
    {
        return new self(new OfferInfo($discountValue, $loyaltyOfferId, $reason));
    }

    /**
     * Sets loyalty Offer Amount field.
     *
     * @param int|null $value
     */
    public function loyaltyOfferAmount(?int $value): self
    {
        $this->instance->setLoyaltyOfferAmount($value);
        return $this;
    }

    /**
     * Sets loyalty Offer Code field.
     *
     * @param string|null $value
     */
    public function loyaltyOfferCode(?string $value): self
    {
        $this->instance->setLoyaltyOfferCode($value);
        return $this;
    }

    /**
     * Sets loyalty Offer Description field.
     *
     * @param string|null $value
     */
    public function loyaltyOfferDescription(?string $value): self
    {
        $this->instance->setLoyaltyOfferDescription($value);
        return $this;
    }

    /**
     * Sets loyalty Offer Type field.
     *
     * @param string|null $value
     */
    public function loyaltyOfferType(?string $value): self
    {
        $this->instance->setLoyaltyOfferType($value);
        return $this;
    }

    /**
     * Sets loyalty Scheme Code field.
     *
     * @param string|null $value
     */
    public function loyaltySchemeCode(?string $value): self
    {
        $this->instance->setLoyaltySchemeCode($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Offer Info object.
     */
    public function build(): OfferInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
