<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\OfferBase;

/**
 * Builder for model OfferBase
 *
 * @see OfferBase
 */
class OfferBaseBuilder
{
    /**
     * @var OfferBase
     */
    private $instance;

    private function __construct(OfferBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offer Base Builder object.
     *
     * @param int $offerId
     * @param string $referenceId
     * @param string $title
     * @param string $description
     */
    public static function init(int $offerId, string $referenceId, string $title, string $description): self
    {
        return new self(new OfferBase($offerId, $referenceId, $title, $description));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Offer Base object.
     */
    public function build(): OfferBase
    {
        return CoreHelper::clone($this->instance);
    }
}
