<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\OfferAssignment;

/**
 * Builder for model OfferAssignment
 *
 * @see OfferAssignment
 */
class OfferAssignmentBuilder
{
    /**
     * @var OfferAssignment
     */
    private $instance;

    private function __construct(OfferAssignment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offer Assignment Builder object.
     *
     * @param string $referenceId
     * @param string $consumerUuid
     * @param string $offerId
     */
    public static function init(string $referenceId, string $consumerUuid, string $offerId): self
    {
        return new self(new OfferAssignment($referenceId, $consumerUuid, $offerId));
    }

    /**
     * Sets valid From field.
     *
     * @param \DateTime|null $value
     */
    public function validFrom(?\DateTime $value): self
    {
        $this->instance->setValidFrom($value);
        return $this;
    }

    /**
     * Sets validity Period field.
     *
     * @param float|null $value
     */
    public function validityPeriod(?float $value): self
    {
        $this->instance->setValidityPeriod($value);
        return $this;
    }

    /**
     * Sets valid To field.
     *
     * @param \DateTime|null $value
     */
    public function validTo(?\DateTime $value): self
    {
        $this->instance->setValidTo($value);
        return $this;
    }

    /**
     * Unsets valid To field.
     */
    public function unsetValidTo(): self
    {
        $this->instance->unsetValidTo();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Offer Assignment object.
     */
    public function build(): OfferAssignment
    {
        return CoreHelper::clone($this->instance);
    }
}
