<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\OfferLanguage;

/**
 * Builder for model OfferLanguage
 *
 * @see OfferLanguage
 */
class OfferLanguageBuilder
{
    /**
     * @var OfferLanguage
     */
    private $instance;

    private function __construct(OfferLanguage $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offer Language Builder object.
     *
     * @param string $id
     * @param string $title
     * @param string $description
     * @param string $customText
     */
    public static function init(string $id, string $title, string $description, string $customText): self
    {
        return new self(new OfferLanguage($id, $title, $description, $customText));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Offer Language object.
     */
    public function build(): OfferLanguage
    {
        return CoreHelper::clone($this->instance);
    }
}
