<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\PointsToCash;

/**
 * Builder for model PointsToCash
 *
 * @see PointsToCash
 */
class PointsToCashBuilder
{
    /**
     * @var PointsToCash
     */
    private $instance;

    private function __construct(PointsToCash $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Points To Cash Builder object.
     */
    public static function init(): self
    {
        return new self(new PointsToCash());
    }

    /**
     * Sets points Redeemed field.
     *
     * @param float|null $value
     */
    public function pointsRedeemed(?float $value): self
    {
        $this->instance->setPointsRedeemed($value);
        return $this;
    }

    /**
     * Sets total Amount field.
     *
     * @param float|null $value
     */
    public function totalAmount(?float $value): self
    {
        $this->instance->setTotalAmount($value);
        return $this;
    }

    /**
     * Sets points To Cash MOP field.
     *
     * @param bool|null $value
     */
    public function pointsToCashMop(?bool $value): self
    {
        $this->instance->setPointsToCashMop($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Points To Cash object.
     */
    public function build(): PointsToCash
    {
        return CoreHelper::clone($this->instance);
    }
}
