<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\RedemptionItem;
use LoyaltyApIsLib\Models\RedemptionRequest;

/**
 * Builder for model RedemptionRequest
 *
 * @see RedemptionRequest
 */
class RedemptionRequestBuilder
{
    /**
     * @var RedemptionRequest
     */
    private $instance;

    private function __construct(RedemptionRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Redemption Request Builder object.
     *
     * @param string $uuid
     * @param string $referenceId
     * @param RedemptionItem[] $redemptionReqArray
     */
    public static function init(string $uuid, string $referenceId, array $redemptionReqArray): self
    {
        return new self(new RedemptionRequest($uuid, $referenceId, $redemptionReqArray));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Redemption Request object.
     */
    public function build(): RedemptionRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
