<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\RedemptionResponse;
use LoyaltyApIsLib\Models\RedemptionResponseItem;

/**
 * Builder for model RedemptionResponse
 *
 * @see RedemptionResponse
 */
class RedemptionResponseBuilder
{
    /**
     * @var RedemptionResponse
     */
    private $instance;

    private function __construct(RedemptionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Redemption Response Builder object.
     *
     * @param string $referenceId
     * @param string $transactionDateTime
     * @param string $updatedPointBalance
     * @param RedemptionResponseItem[] $redemptionReqArray
     */
    public static function init(
        string $referenceId,
        string $transactionDateTime,
        string $updatedPointBalance,
        array $redemptionReqArray
    ): self {
        return new self(
            new RedemptionResponse($referenceId, $transactionDateTime, $updatedPointBalance, $redemptionReqArray)
        );
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Redemption Response object.
     */
    public function build(): RedemptionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
