<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\RedemptionItem;

/**
 * Builder for model RedemptionItem
 *
 * @see RedemptionItem
 */
class RedemptionItemBuilder
{
    /**
     * @var RedemptionItem
     */
    private $instance;

    private function __construct(RedemptionItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Redemption Item Builder object.
     *
     * @param string $itemId
     * @param int $points
     * @param string $reasonForRedemption
     */
    public static function init(string $itemId, int $points, string $reasonForRedemption): self
    {
        return new self(new RedemptionItem($itemId, $points, $reasonForRedemption));
    }

    /**
     * Sets quantity field.
     *
     * @param int|null $value
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Redemption Item object.
     */
    public function build(): RedemptionItem
    {
        return CoreHelper::clone($this->instance);
    }
}
