<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\OfferInfo;
use LoyaltyApIsLib\Models\OfferLanguage;
use LoyaltyApIsLib\Models\RedeemedItem;
use LoyaltyApIsLib\Models\RedeemedItemProduct;
use LoyaltyApIsLib\Models\VoucherItem;

/**
 * Builder for model RedeemedItem
 *
 * @see RedeemedItem
 */
class RedeemedItemBuilder
{
    /**
     * @var RedeemedItem
     */
    private $instance;

    private function __construct(RedeemedItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Redeemed Item Builder object.
     *
     * @param float $amount
     * @param string $detailType
     * @param float $discountAmount
     * @param OfferInfo[] $offerInfos
     * @param float $originalAmount
     * @param RedeemedItemProduct $productData
     * @param float $quantity
     */
    public static function init(
        float $amount,
        string $detailType,
        float $discountAmount,
        array $offerInfos,
        float $originalAmount,
        RedeemedItemProduct $productData,
        float $quantity
    ): self {
        return new self(new RedeemedItem(
            $amount,
            $detailType,
            $discountAmount,
            $offerInfos,
            $originalAmount,
            $productData,
            $quantity
        ));
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets offer Lang field.
     *
     * @param OfferLanguage|null $value
     */
    public function offerLang(?OfferLanguage $value): self
    {
        $this->instance->setOfferLang($value);
        return $this;
    }

    /**
     * Sets vat Amount field.
     *
     * @param float|null $value
     */
    public function vatAmount(?float $value): self
    {
        $this->instance->setVatAmount($value);
        return $this;
    }

    /**
     * Sets vat Rate field.
     *
     * @param float|null $value
     */
    public function vatRate(?float $value): self
    {
        $this->instance->setVatRate($value);
        return $this;
    }

    /**
     * Sets points field.
     *
     * @param int|null $value
     */
    public function points(?int $value): self
    {
        $this->instance->setPoints($value);
        return $this;
    }

    /**
     * Sets vouchers field.
     *
     * @param string[]|null $value
     */
    public function vouchers(?array $value): self
    {
        $this->instance->setVouchers($value);
        return $this;
    }

    /**
     * Sets voucher Items field.
     *
     * @param VoucherItem[]|null $value
     */
    public function voucherItems(?array $value): self
    {
        $this->instance->setVoucherItems($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Redeemed Item object.
     */
    public function build(): RedeemedItem
    {
        return CoreHelper::clone($this->instance);
    }
}
