<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\RedemptionResponseItem;

/**
 * Builder for model RedemptionResponseItem
 *
 * @see RedemptionResponseItem
 */
class RedemptionResponseItemBuilder
{
    /**
     * @var RedemptionResponseItem
     */
    private $instance;

    private function __construct(RedemptionResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Redemption Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new RedemptionResponseItem());
    }

    /**
     * Sets item Id field.
     *
     * @param string|null $value
     */
    public function itemId(?string $value): self
    {
        $this->instance->setItemId($value);
        return $this;
    }

    /**
     * Sets quantity field.
     *
     * @param int|null $value
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Sets points field.
     *
     * @param int|null $value
     */
    public function points(?int $value): self
    {
        $this->instance->setPoints($value);
        return $this;
    }

    /**
     * Sets reason For Redemption field.
     *
     * @param string|null $value
     */
    public function reasonForRedemption(?string $value): self
    {
        $this->instance->setReasonForRedemption($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Redemption Response Item object.
     */
    public function build(): RedemptionResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
