<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\RefreshTokenRequest;

/**
 * Builder for model RefreshTokenRequest
 *
 * @see RefreshTokenRequest
 */
class RefreshTokenRequestBuilder
{
    /**
     * @var RefreshTokenRequest
     */
    private $instance;

    private function __construct(RefreshTokenRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Refresh Token Request Builder object.
     *
     * @param string $refreshToken
     */
    public static function init(string $refreshToken): self
    {
        return new self(new RefreshTokenRequest($refreshToken));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Refresh Token Request object.
     */
    public function build(): RefreshTokenRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
