<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\RefreshTokenResponse;

/**
 * Builder for model RefreshTokenResponse
 *
 * @see RefreshTokenResponse
 */
class RefreshTokenResponseBuilder
{
    /**
     * @var RefreshTokenResponse
     */
    private $instance;

    private function __construct(RefreshTokenResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Refresh Token Response Builder object.
     *
     * @param string $accessToken
     * @param string $refreshToken
     * @param int $expiresIn
     */
    public static function init(string $accessToken, string $refreshToken, int $expiresIn): self
    {
        return new self(new RefreshTokenResponse($accessToken, $refreshToken, $expiresIn));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Refresh Token Response object.
     */
    public function build(): RefreshTokenResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
