<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\SaleItemProduct;

/**
 * Builder for model SaleItemProduct
 *
 * @see SaleItemProduct
 */
class SaleItemProductBuilder
{
    /**
     * @var SaleItemProduct
     */
    private $instance;

    private function __construct(SaleItemProduct $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Sale Item Product Builder object.
     *
     * @param string $id
     * @param string $name
     * @param string $productType
     */
    public static function init(string $id, string $name, string $productType): self
    {
        return new self(new SaleItemProduct($id, $name, $productType));
    }

    /**
     * Sets product Code field.
     *
     * @param string|null $value
     */
    public function productCode(?string $value): self
    {
        $this->instance->setProductCode($value);
        return $this;
    }

    /**
     * Sets product Description field.
     *
     * @param string|null $value
     */
    public function productDescription(?string $value): self
    {
        $this->instance->setProductDescription($value);
        return $this;
    }

    /**
     * Sets additional Product Description field.
     *
     * @param string|null $value
     */
    public function additionalProductDescription(?string $value): self
    {
        $this->instance->setAdditionalProductDescription($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Sale Item Product object.
     */
    public function build(): SaleItemProduct
    {
        return CoreHelper::clone($this->instance);
    }
}
