<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\EvChargingDetails;
use LoyaltyApIsLib\Models\OfferInfo;
use LoyaltyApIsLib\Models\OfferLanguage;
use LoyaltyApIsLib\Models\SaleItem;
use LoyaltyApIsLib\Models\SaleItemProduct;
use LoyaltyApIsLib\Models\VoucherItem;

/**
 * Builder for model SaleItem
 *
 * @see SaleItem
 */
class SaleItemBuilder
{
    /**
     * @var SaleItem
     */
    private $instance;

    private function __construct(SaleItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Sale Item Builder object.
     *
     * @param float $amount
     * @param string $detailType
     * @param float $discountAmount
     * @param OfferInfo[] $offerInfos
     * @param float $originalAmount
     * @param SaleItemProduct $productData
     * @param float $quantity
     */
    public static function init(
        float $amount,
        string $detailType,
        float $discountAmount,
        array $offerInfos,
        float $originalAmount,
        SaleItemProduct $productData,
        float $quantity
    ): self {
        return new self(
            new SaleItem(
                $amount,
                $detailType,
                $discountAmount,
                $offerInfos,
                $originalAmount,
                $productData,
                $quantity
            )
        );
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets offer Lang field.
     *
     * @param OfferLanguage|null $value
     */
    public function offerLang(?OfferLanguage $value): self
    {
        $this->instance->setOfferLang($value);
        return $this;
    }

    /**
     * Sets original Net Amount field.
     *
     * @param float|null $value
     */
    public function originalNetAmount(?float $value): self
    {
        $this->instance->setOriginalNetAmount($value);
        return $this;
    }

    /**
     * Sets vat Amount field.
     *
     * @param float|null $value
     */
    public function vatAmount(?float $value): self
    {
        $this->instance->setVatAmount($value);
        return $this;
    }

    /**
     * Sets vat Rate field.
     *
     * @param float|null $value
     */
    public function vatRate(?float $value): self
    {
        $this->instance->setVatRate($value);
        return $this;
    }

    /**
     * Sets voucher Items field.
     *
     * @param VoucherItem[]|null $value
     */
    public function voucherItems(?array $value): self
    {
        $this->instance->setVoucherItems($value);
        return $this;
    }

    /**
     * Sets vouchers field.
     *
     * @param string[]|null $value
     */
    public function vouchers(?array $value): self
    {
        $this->instance->setVouchers($value);
        return $this;
    }

    /**
     * Sets unit Price field.
     *
     * @param float|null $value
     */
    public function unitPrice(?float $value): self
    {
        $this->instance->setUnitPrice($value);
        return $this;
    }

    /**
     * Sets unit Measure field.
     *
     * @param string|null $value
     */
    public function unitMeasure(?string $value): self
    {
        $this->instance->setUnitMeasure($value);
        return $this;
    }

    /**
     * Sets EV field.
     *
     * @param EvChargingDetails|null $value
     */
    public function ev(?EvChargingDetails $value): self
    {
        $this->instance->setEv($value);
        return $this;
    }

    /**
     * Sets points field.
     *
     * @param int|null $value
     */
    public function points(?int $value): self
    {
        $this->instance->setPoints($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Sale Item object.
     */
    public function build(): SaleItem
    {
        return CoreHelper::clone($this->instance);
    }
}
