<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\SiteData;

/**
 * Builder for model SiteData
 *
 * @see SiteData
 */
class SiteDataBuilder
{
    /**
     * @var SiteData
     */
    private $instance;

    private function __construct(SiteData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Site Data Builder object.
     *
     * @param string $countryCode
     * @param string $siteId
     * @param string $name
     */
    public static function init(string $countryCode, string $siteId, string $name): self
    {
        return new self(new SiteData($countryCode, $siteId, $name));
    }

    /**
     * Sets postcode field.
     *
     * @param string|null $value
     */
    public function postcode(?string $value): self
    {
        $this->instance->setPostcode($value);
        return $this;
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets address field.
     *
     * @param string|null $value
     */
    public function address(?string $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Site Data object.
     */
    public function build(): SiteData
    {
        return CoreHelper::clone($this->instance);
    }
}
