<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\Transaction;
use LoyaltyApIsLib\Models\TransactionsResponse;

/**
 * Builder for model TransactionsResponse
 *
 * @see TransactionsResponse
 */
class TransactionsResponseBuilder
{
    /**
     * @var TransactionsResponse
     */
    private $instance;

    private function __construct(TransactionsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transactions Response Builder object.
     *
     * @param int $totalResults
     * @param string $nextPage
     * @param string $previousPage
     * @param float $totalSaved
     * @param Transaction[] $transactions
     */
    public static function init(
        int $totalResults,
        string $nextPage,
        string $previousPage,
        float $totalSaved,
        array $transactions
    ): self {
        return new self(
            new TransactionsResponse($totalResults, $nextPage, $previousPage, $totalSaved, $transactions)
        );
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Transactions Response object.
     */
    public function build(): TransactionsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
