<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\TransactionBalance;
use LoyaltyApIsLib\Models\TransactionBalanceAmount;

/**
 * Builder for model TransactionBalance
 *
 * @see TransactionBalance
 */
class TransactionBalanceBuilder
{
    /**
     * @var TransactionBalance
     */
    private $instance;

    private function __construct(TransactionBalance $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transaction Balance Builder object.
     *
     * @param string $currencyType
     * @param TransactionBalanceAmount[] $amounts
     */
    public static function init(string $currencyType, array $amounts): self
    {
        return new self(new TransactionBalance($currencyType, $amounts));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Transaction Balance object.
     */
    public function build(): TransactionBalance
    {
        return CoreHelper::clone($this->instance);
    }
}
