<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\CurrencyData;
use LoyaltyApIsLib\Models\LoyaltyCardInfo;
use LoyaltyApIsLib\Models\PointsToCash;
use LoyaltyApIsLib\Models\RedeemedItem;
use LoyaltyApIsLib\Models\SaleItem;
use LoyaltyApIsLib\Models\SiteData;
use LoyaltyApIsLib\Models\Transaction;
use LoyaltyApIsLib\Models\TransactionBalance;
use LoyaltyApIsLib\Models\TransactionVoucher;

/**
 * Builder for model Transaction
 *
 * @see Transaction
 */
class TransactionBuilder
{
    /**
     * @var Transaction
     */
    private $instance;

    private function __construct(Transaction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transaction Builder object.
     *
     * @param int $transactionDateTime
     * @param SiteData $siteData
     * @param LoyaltyCardInfo $loyalty
     * @param float $totalAmount
     * @param float $totalDiscountAmount
     * @param float $totalDiscountedFullAmount
     * @param SaleItem[] $saleItems
     * @param RedeemedItem[] $redeemedItems
     * @param TransactionVoucher[] $transactionVouchers
     */
    public static function init(
        int $transactionDateTime,
        SiteData $siteData,
        LoyaltyCardInfo $loyalty,
        float $totalAmount,
        float $totalDiscountAmount,
        float $totalDiscountedFullAmount,
        array $saleItems,
        array $redeemedItems,
        array $transactionVouchers
    ): self {
        return new self(new Transaction(
            $transactionDateTime,
            $siteData,
            $loyalty,
            $totalAmount,
            $totalDiscountAmount,
            $totalDiscountedFullAmount,
            $saleItems,
            $redeemedItems,
            $transactionVouchers
        ));
    }

    /**
     * Sets transaction Date Time Stamp field.
     *
     * @param \DateTime|null $value
     */
    public function transactionDateTimeStamp(?\DateTime $value): self
    {
        $this->instance->setTransactionDateTimeStamp($value);
        return $this;
    }

    /**
     * Sets transaction Id field.
     *
     * @param string|null $value
     */
    public function transactionId(?string $value): self
    {
        $this->instance->setTransactionId($value);
        return $this;
    }

    /**
     * Sets partner Code field.
     *
     * @param string|null $value
     */
    public function partnerCode(?string $value): self
    {
        $this->instance->setPartnerCode($value);
        return $this;
    }

    /**
     * Sets partner Name field.
     *
     * @param string|null $value
     */
    public function partnerName(?string $value): self
    {
        $this->instance->setPartnerName($value);
        return $this;
    }

    /**
     * Sets partner Logo field.
     *
     * @param string|null $value
     */
    public function partnerLogo(?string $value): self
    {
        $this->instance->setPartnerLogo($value);
        return $this;
    }

    /**
     * Sets reference Id field.
     *
     * @param string|null $value
     */
    public function referenceId(?string $value): self
    {
        $this->instance->setReferenceId($value);
        return $this;
    }

    /**
     * Sets total Vat Amount field.
     *
     * @param float|null $value
     */
    public function totalVatAmount(?float $value): self
    {
        $this->instance->setTotalVatAmount($value);
        return $this;
    }

    /**
     * Sets balances field.
     *
     * @param TransactionBalance[]|null $value
     */
    public function balances(?array $value): self
    {
        $this->instance->setBalances($value);
        return $this;
    }

    /**
     * Sets currency Code field.
     *
     * @param string|null $value
     */
    public function currencyCode(?string $value): self
    {
        $this->instance->setCurrencyCode($value);
        return $this;
    }

    /**
     * Sets receipt Number field.
     *
     * @param string|null $value
     */
    public function receiptNumber(?string $value): self
    {
        $this->instance->setReceiptNumber($value);
        return $this;
    }

    /**
     * Sets points To Cash field.
     *
     * @param PointsToCash|null $value
     */
    public function pointsToCash(?PointsToCash $value): self
    {
        $this->instance->setPointsToCash($value);
        return $this;
    }

    /**
     * Sets company Id field.
     *
     * @param int|null $value
     */
    public function companyId(?int $value): self
    {
        $this->instance->setCompanyId($value);
        return $this;
    }

    /**
     * Sets is Partner Redemption field.
     *
     * @param bool|null $value
     */
    public function isPartnerRedemption(?bool $value): self
    {
        $this->instance->setIsPartnerRedemption($value);
        return $this;
    }

    /**
     * Sets currency Data field.
     *
     * @param CurrencyData|null $value
     */
    public function currencyData(?CurrencyData $value): self
    {
        $this->instance->setCurrencyData($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Transaction object.
     */
    public function build(): Transaction
    {
        return CoreHelper::clone($this->instance);
    }
}
