<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\TransactionVoucher;

/**
 * Builder for model TransactionVoucher
 *
 * @see TransactionVoucher
 */
class TransactionVoucherBuilder
{
    /**
     * @var TransactionVoucher
     */
    private $instance;

    private function __construct(TransactionVoucher $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transaction Voucher Builder object.
     *
     * @param string $detailType
     * @param string $code
     * @param string $name
     * @param float $amount
     * @param float $quantity
     */
    public static function init(string $detailType, string $code, string $name, float $amount, float $quantity): self
    {
        return new self(new TransactionVoucher($detailType, $code, $name, $amount, $quantity));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Transaction Voucher object.
     */
    public function build(): TransactionVoucher
    {
        return CoreHelper::clone($this->instance);
    }
}
