<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\TransactionBalanceAmount;

/**
 * Builder for model TransactionBalanceAmount
 *
 * @see TransactionBalanceAmount
 */
class TransactionBalanceAmountBuilder
{
    /**
     * @var TransactionBalanceAmount
     */
    private $instance;

    private function __construct(TransactionBalanceAmount $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transaction Balance Amount Builder object.
     *
     * @param float $amount
     * @param string $state
     */
    public static function init(float $amount, string $state): self
    {
        return new self(new TransactionBalanceAmount($amount, $state));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Transaction Balance Amount object.
     */
    public function build(): TransactionBalanceAmount
    {
        return CoreHelper::clone($this->instance);
    }
}
