<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\ErrorInfo;
use LoyaltyApIsLib\Models\UnprocessableEntityErrorResponse;

/**
 * Builder for model UnprocessableEntityErrorResponse
 *
 * @see UnprocessableEntityErrorResponse
 */
class UnprocessableEntityErrorResponseBuilder
{
    /**
     * @var UnprocessableEntityErrorResponse
     */
    private $instance;

    private function __construct(UnprocessableEntityErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Unprocessable Entity Error Response Builder object.
     *
     * @param float $errorCode
     * @param string $message
     * @param ErrorInfo $error
     */
    public static function init(float $errorCode, string $message, ErrorInfo $error): self
    {
        return new self(new UnprocessableEntityErrorResponse($errorCode, $message, $error));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Unprocessable Entity Error Response object.
     */
    public function build(): UnprocessableEntityErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
