<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Models\VoucherItem;

/**
 * Builder for model VoucherItem
 *
 * @see VoucherItem
 */
class VoucherItemBuilder
{
    /**
     * @var VoucherItem
     */
    private $instance;

    private function __construct(VoucherItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Voucher Item Builder object.
     *
     * @param string $code
     * @param int $expiryDate
     * @param \DateTime $expiryDateTimestamp
     */
    public static function init(string $code, int $expiryDate, \DateTime $expiryDateTimestamp): self
    {
        return new self(new VoucherItem($code, $expiryDate, $expiryDateTimestamp));
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Voucher Item object.
     */
    public function build(): VoucherItem
    {
        return CoreHelper::clone($this->instance);
    }
}
