<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Exceptions;

use LoyaltyApIsLib\ApiHelper;

class CommonErrorException extends ApiException
{
    /**
     * @var float
     */
    private $errorCode;

    /**
     * @var string
     */
    private $messageProperty;

    /**
     * @var \LoyaltyApIsLib\Models\ErrorBaseContainer
     */
    private $error;

    /**
     * @param string $reason
     * @param \LoyaltyApIsLib\Http\HttpRequest $request
     * @param \LoyaltyApIsLib\Http\HttpResponse $response
     * @param float $errorCode
     * @param string $messageProperty
     * @param \LoyaltyApIsLib\Models\ErrorBaseContainer $error
     */
    public function __construct(
        string $reason,
        \LoyaltyApIsLib\Http\HttpRequest $request,
        \LoyaltyApIsLib\Http\HttpResponse $response,
        float $errorCode,
        string $messageProperty,
        \LoyaltyApIsLib\Models\ErrorBaseContainer $error
    ) {
        parent::__construct($reason, $request, $response);
        $this->errorCode = $errorCode;
        $this->messageProperty = $messageProperty;
        $this->error = $error;
    }

    /**
     * Returns Error Code.
     * custom error code for developer or user
     * Note: One of the following values will be returned:
     * 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1010, 1011, 1012, 1014, 1015, 1016
     */
    public function getErrorCode(): float
    {
        return $this->errorCode;
    }

    /**
     * Sets Error Code.
     * custom error code for developer or user
     * Note: One of the following values will be returned:
     * 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1010, 1011, 1012, 1014, 1015, 1016
     *
     * @required
     * @maps errorCode
     */
    public function setErrorCode(float $errorCode): void
    {
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Message Property.
     * Custom error message <br>
     * Note: One of the following values will be returned:
     * - Offer does not exist
     * - Customer does not exist
     * - Valid from date is invalid
     * - ValidityPeriod is invalid
     * - Offer is by default assigned to all customers, which cannot be changed.
     * - Assignment is not allowed
     * - Customer assign should have validity dates.
     * - Customer assign validity start date should be before the validity end date.
     * - Customer assign validity dates must be between the offer assignable dates.
     * - Offer validity start date should not be in the past.
     * - Customer already assigned to this offer.
     * - Offer module is disabled
     * - Partner code is not valid for this offer
     * - Reference ID already used
     * - Partner assignment already ended for this customer
     */
    public function getMessageProperty(): string
    {
        return $this->messageProperty;
    }

    /**
     * Sets Message Property.
     * Custom error message <br>
     * Note: One of the following values will be returned:
     * - Offer does not exist
     * - Customer does not exist
     * - Valid from date is invalid
     * - ValidityPeriod is invalid
     * - Offer is by default assigned to all customers, which cannot be changed.
     * - Assignment is not allowed
     * - Customer assign should have validity dates.
     * - Customer assign validity start date should be before the validity end date.
     * - Customer assign validity dates must be between the offer assignable dates.
     * - Offer validity start date should not be in the past.
     * - Customer already assigned to this offer.
     * - Offer module is disabled
     * - Partner code is not valid for this offer
     * - Reference ID already used
     * - Partner assignment already ended for this customer
     *
     * @required
     * @maps message
     */
    public function setMessageProperty(string $messageProperty): void
    {
        $this->messageProperty = $messageProperty;
    }

    /**
     * Returns Error.
     */
    public function getError(): \LoyaltyApIsLib\Models\ErrorBaseContainer
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @required
     * @maps error
     */
    public function setError(\LoyaltyApIsLib\Models\ErrorBaseContainer $error): void
    {
        $this->error = $error;
    }

    /**
     * Converts the CommonErrorException object to a human-readable string representation.
     *
     * @return string The string representation of the CommonErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CommonErrorException',
            [
                'errorCode' => $this->errorCode,
                'messageProperty' => $this->messageProperty,
                'error' => $this->error,
                'additionalProperties' => $this->additionalProperties
            ],
            parent::__toString()
        );
    }

    protected $propertyNames = ['errorCode', 'message', 'error'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
