<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Exceptions;

use LoyaltyApIsLib\ApiHelper;

class JsonApiErrorException extends ApiException
{
    /**
     * @var \LoyaltyApIsLib\Models\JsonApiVersion|null
     */
    private $jsonapi;

    /**
     * @var \LoyaltyApIsLib\Models\ErrorItem[]|null
     */
    private $errors;

    /**
     * Returns Jsonapi.
     */
    public function getJsonapi(): ?\LoyaltyApIsLib\Models\JsonApiVersion
    {
        return $this->jsonapi;
    }

    /**
     * Sets Jsonapi.
     *
     * @maps jsonapi
     */
    public function setJsonapi(?\LoyaltyApIsLib\Models\JsonApiVersion $jsonapi): void
    {
        $this->jsonapi = $jsonapi;
    }

    /**
     * Returns Errors.
     *
     * @return \LoyaltyApIsLib\Models\ErrorItem[]|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     *
     * @maps errors
     *
     * @param \LoyaltyApIsLib\Models\ErrorItem[]|null $errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }

    /**
     * Converts the JsonApiErrorException object to a human-readable string representation.
     *
     * @return string The string representation of the JsonApiErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'JsonApiErrorException',
            [
                'jsonapi' => $this->jsonapi,
                'errors' => $this->errors,
                'additionalProperties' => $this->additionalProperties
            ],
            parent::__toString()
        );
    }

    protected $propertyNames = ['jsonapi', 'errors'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
