<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Exceptions;

use LoyaltyApIsLib\ApiHelper;

class ResourceNotFoundErrorException extends ApiException
{
    /**
     * @var float
     */
    private $errorCode;

    /**
     * @var string
     */
    private $messageProperty;

    /**
     * @var \LoyaltyApIsLib\Models\ErrorInfo
     */
    private $error;

    /**
     * @param string $reason
     * @param \LoyaltyApIsLib\Http\HttpRequest $request
     * @param \LoyaltyApIsLib\Http\HttpResponse $response
     * @param float $errorCode
     * @param string $messageProperty
     * @param \LoyaltyApIsLib\Models\ErrorInfo $error
     */
    public function __construct(
        string $reason,
        \LoyaltyApIsLib\Http\HttpRequest $request,
        \LoyaltyApIsLib\Http\HttpResponse $response,
        float $errorCode,
        string $messageProperty,
        \LoyaltyApIsLib\Models\ErrorInfo $error
    ) {
        parent::__construct($reason, $request, $response);
        $this->errorCode = $errorCode;
        $this->messageProperty = $messageProperty;
        $this->error = $error;
    }

    /**
     * Returns Error Code.
     * HTTP error status code
     */
    public function getErrorCode(): float
    {
        return $this->errorCode;
    }

    /**
     * Sets Error Code.
     * HTTP error status code
     *
     * @required
     * @maps errorCode
     */
    public function setErrorCode(float $errorCode): void
    {
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Message Property.
     * HTTP error status message
     */
    public function getMessageProperty(): string
    {
        return $this->messageProperty;
    }

    /**
     * Sets Message Property.
     * HTTP error status message
     *
     * @required
     * @maps message
     */
    public function setMessageProperty(string $messageProperty): void
    {
        $this->messageProperty = $messageProperty;
    }

    /**
     * Returns Error.
     */
    public function getError(): \LoyaltyApIsLib\Models\ErrorInfo
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @required
     * @maps error
     */
    public function setError(\LoyaltyApIsLib\Models\ErrorInfo $error): void
    {
        $this->error = $error;
    }

    /**
     * Converts the ResourceNotFoundErrorException object to a human-readable string representation.
     *
     * @return string The string representation of the ResourceNotFoundErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResourceNotFoundErrorException',
            [
                'errorCode' => $this->errorCode,
                'messageProperty' => $this->messageProperty,
                'error' => $this->error,
                'additionalProperties' => $this->additionalProperties
            ],
            parent::__toString()
        );
    }

    protected $propertyNames = ['errorCode', 'message', 'error'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
