<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class AccessCodeResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accessCode;

    /**
     * @var int|null
     */
    private $expiresIn;

    /**
     * Returns Access Code.
     * AccessCode provided by Shell after it redirects the user to the partner's URL.
     */
    public function getAccessCode(): ?string
    {
        return $this->accessCode;
    }

    /**
     * Sets Access Code.
     * AccessCode provided by Shell after it redirects the user to the partner's URL.
     *
     * @maps accessCode
     */
    public function setAccessCode(?string $accessCode): void
    {
        $this->accessCode = $accessCode;
    }

    /**
     * Returns Expires In.
     * Indicates the number of seconds until the accessCode expires
     */
    public function getExpiresIn(): ?int
    {
        return $this->expiresIn;
    }

    /**
     * Sets Expires In.
     * Indicates the number of seconds until the accessCode expires
     *
     * @maps expiresIn
     */
    public function setExpiresIn(?int $expiresIn): void
    {
        $this->expiresIn = $expiresIn;
    }

    /**
     * Converts the AccessCodeResponse object to a human-readable string representation.
     *
     * @return string The string representation of the AccessCodeResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AccessCodeResponse',
            [
                'accessCode' => $this->accessCode,
                'expiresIn' => $this->expiresIn,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['accessCode', 'expiresIn'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accessCode)) {
            $json['accessCode'] = $this->accessCode;
        }
        if (isset($this->expiresIn)) {
            $json['expiresIn']  = $this->expiresIn;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
