<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class AuthTokenResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $token;

    /**
     * @var string|null
     */
    private $tokenType;

    /**
     * @var string|null
     */
    private $expiresIn;

    /**
     * @var string|null
     */
    private $owner;

    /**
     * Returns Token.
     * Your Basic public token which needs to be used in the auth/ExchangeAccessCode.
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * Your Basic public token which needs to be used in the auth/ExchangeAccessCode.
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Token Type.
     * Type of the token.
     */
    public function getTokenType(): ?string
    {
        return $this->tokenType;
    }

    /**
     * Sets Token Type.
     * Type of the token.
     *
     * @maps tokenType
     */
    public function setTokenType(?string $tokenType): void
    {
        $this->tokenType = $tokenType;
    }

    /**
     * Returns Expires In.
     * With value **unlimited** it means this token will never expire
     */
    public function getExpiresIn(): ?string
    {
        return $this->expiresIn;
    }

    /**
     * Sets Expires In.
     * With value **unlimited** it means this token will never expire
     *
     * @maps expiresIn
     */
    public function setExpiresIn(?string $expiresIn): void
    {
        $this->expiresIn = $expiresIn;
    }

    /**
     * Returns Owner.
     * States the name of the partner to which the digest used belongs
     */
    public function getOwner(): ?string
    {
        return $this->owner;
    }

    /**
     * Sets Owner.
     * States the name of the partner to which the digest used belongs
     *
     * @maps owner
     */
    public function setOwner(?string $owner): void
    {
        $this->owner = $owner;
    }

    /**
     * Converts the AuthTokenResponse object to a human-readable string representation.
     *
     * @return string The string representation of the AuthTokenResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthTokenResponse',
            [
                'token' => $this->token,
                'tokenType' => $this->tokenType,
                'expiresIn' => $this->expiresIn,
                'owner' => $this->owner,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['token', 'tokenType', 'expiresIn', 'owner'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->token)) {
            $json['token']     = $this->token;
        }
        if (isset($this->tokenType)) {
            $json['tokenType'] = $this->tokenType;
        }
        if (isset($this->expiresIn)) {
            $json['expiresIn'] = $this->expiresIn;
        }
        if (isset($this->owner)) {
            $json['owner']     = $this->owner;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
