<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use LoyaltyApIsLib\Utils\DateTimeHelper;
use stdClass;

class BalanceAmountDetail implements \JsonSerializable
{
    /**
     * @var float
     */
    private $amount;

    /**
     * @var string
     */
    private $state;

    /**
     * @var \DateTime
     */
    private $dateTime;

    /**
     * @var int
     */
    private $dateTimestamp;

    /**
     * @var float|null
     */
    private $cashAmount;

    /**
     * @var int|null
     */
    private $period;

    /**
     * @var int[]|null
     */
    private $position;

    /**
     * @param float $amount
     * @param string $state
     * @param \DateTime $dateTime
     * @param int $dateTimestamp
     */
    public function __construct(float $amount, string $state, \DateTime $dateTime, int $dateTimestamp)
    {
        $this->amount = $amount;
        $this->state = $state;
        $this->dateTime = $dateTime;
        $this->dateTimestamp = $dateTimestamp;
    }

    /**
     * Returns Amount.
     * Current value of specified balance.
     */
    public function getAmount(): float
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Current value of specified balance.
     *
     * @required
     * @maps amount
     */
    public function setAmount(float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns State.
     * State of the points balance amount.
     */
    public function getState(): string
    {
        return $this->state;
    }

    /**
     * Sets State.
     * State of the points balance amount.
     *
     * @required
     * @maps state
     * @factory \LoyaltyApIsLib\Models\BalanceState::checkValue
     */
    public function setState(string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Date Time.
     * Expiration Date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ” Nullable.
     */
    public function getDateTime(): \DateTime
    {
        return $this->dateTime;
    }

    /**
     * Sets Date Time.
     * Expiration Date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ” Nullable.
     *
     * @required
     * @maps dateTime
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateTime(\DateTime $dateTime): void
    {
        $this->dateTime = $dateTime;
    }

    /**
     * Returns Date Timestamp.
     * Date as Unix epoch (UTC).
     */
    public function getDateTimestamp(): int
    {
        return $this->dateTimestamp;
    }

    /**
     * Sets Date Timestamp.
     * Date as Unix epoch (UTC).
     *
     * @required
     * @maps dateTimestamp
     */
    public function setDateTimestamp(int $dateTimestamp): void
    {
        $this->dateTimestamp = $dateTimestamp;
    }

    /**
     * Returns Cash Amount.
     * Point to cash exchange amnount.
     */
    public function getCashAmount(): ?float
    {
        return $this->cashAmount;
    }

    /**
     * Sets Cash Amount.
     * Point to cash exchange amnount.
     *
     * @maps cashAmount
     */
    public function setCashAmount(?float $cashAmount): void
    {
        $this->cashAmount = $cashAmount;
    }

    /**
     * Returns Period.
     * Period of expiration, minimum value is 1. Seralized only when it’s not null.
     */
    public function getPeriod(): ?int
    {
        return $this->period;
    }

    /**
     * Sets Period.
     * Period of expiration, minimum value is 1. Seralized only when it’s not null.
     *
     * @maps period
     */
    public function setPeriod(?int $period): void
    {
        $this->period = $period;
    }

    /**
     * Returns Position.
     * The list of numbers describes an index of boost’s position in qualifying visit, Seralized only when
     * it’s not null and not empty.
     *
     * @return int[]|null
     */
    public function getPosition(): ?array
    {
        return $this->position;
    }

    /**
     * Sets Position.
     * The list of numbers describes an index of boost’s position in qualifying visit, Seralized only when
     * it’s not null and not empty.
     *
     * @maps position
     *
     * @param int[]|null $position
     */
    public function setPosition(?array $position): void
    {
        $this->position = $position;
    }

    /**
     * Converts the BalanceAmountDetail object to a human-readable string representation.
     *
     * @return string The string representation of the BalanceAmountDetail object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BalanceAmountDetail',
            [
                'amount' => $this->amount,
                'state' => $this->state,
                'dateTime' => $this->dateTime,
                'dateTimestamp' => $this->dateTimestamp,
                'cashAmount' => $this->cashAmount,
                'period' => $this->period,
                'position' => $this->position,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['amount', 'state', 'dateTime', 'dateTimestamp', 'cashAmount', 'period', 'position'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount']         = $this->amount;
        $json['state']          = BalanceState::checkValue($this->state);
        $json['dateTime']       = DateTimeHelper::toRfc3339DateTime($this->dateTime);
        $json['dateTimestamp']  = $this->dateTimestamp;
        if (isset($this->cashAmount)) {
            $json['cashAmount'] = $this->cashAmount;
        }
        if (isset($this->period)) {
            $json['period']     = $this->period;
        }
        if (isset($this->position)) {
            $json['position']   = $this->position;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
