<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

/**
 * List of Balances for the customer
 */
class BalanceAmount implements \JsonSerializable
{
    /**
     * @var BalanceCurrencyAmount[]|null
     */
    private $amounts;

    /**
     * Returns Amounts.
     *
     * @return BalanceCurrencyAmount[]|null
     */
    public function getAmounts(): ?array
    {
        return $this->amounts;
    }

    /**
     * Sets Amounts.
     *
     * @maps amounts
     *
     * @param BalanceCurrencyAmount[]|null $amounts
     */
    public function setAmounts(?array $amounts): void
    {
        $this->amounts = $amounts;
    }

    /**
     * Converts the BalanceAmount object to a human-readable string representation.
     *
     * @return string The string representation of the BalanceAmount object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BalanceAmount',
            ['amounts' => $this->amounts, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['amounts'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->amounts)) {
            $json['amounts'] = $this->amounts;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
