<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * State of the points balance amount.
 */
class BalanceState
{
    public const AVAILABLE = 'AVAILABLE';

    public const EXPIRING = 'EXPIRING';

    public const RESERVED = 'RESERVED';

    public const TARGET = 'TARGET';

    public const BOOST = 'BOOST';

    public const CHANGE = 'CHANGE';

    public const TOTAL_SPENT = 'TOTAL_SPENT';

    public const EARNED = 'EARNED';

    public const REDEEMED = 'REDEEMED';

    public const TOTAL = 'TOTAL';

    public const LAST = 'LAST';

    private const _ALL_VALUES = [
        self::AVAILABLE,
        self::EXPIRING,
        self::RESERVED,
        self::TARGET,
        self::BOOST,
        self::CHANGE,
        self::TOTAL_SPENT,
        self::EARNED,
        self::REDEEMED,
        self::TOTAL,
        self::LAST
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for BalanceState.");
    }
}
