<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

/**
 * currencyData is only filled, where there is possible non-same currency cross-border transaction
 */
class CurrencyData implements \JsonSerializable
{
    /**
     * @var string
     */
    private $code;

    /**
     * @var string
     */
    private $symbol;

    /**
     * @var bool
     */
    private $isSuffix;

    /**
     * @var bool
     */
    private $hasSpace;

    /**
     * @param string $code
     * @param string $symbol
     * @param bool $isSuffix
     * @param bool $hasSpace
     */
    public function __construct(string $code, string $symbol, bool $isSuffix, bool $hasSpace)
    {
        $this->code = $code;
        $this->symbol = $symbol;
        $this->isSuffix = $isSuffix;
        $this->hasSpace = $hasSpace;
    }

    /**
     * Returns Code.
     * Currency code
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     * Currency code
     *
     * @required
     * @maps code
     */
    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Symbol.
     * Currency symbol
     */
    public function getSymbol(): string
    {
        return $this->symbol;
    }

    /**
     * Sets Symbol.
     * Currency symbol
     *
     * @required
     * @maps symbol
     */
    public function setSymbol(string $symbol): void
    {
        $this->symbol = $symbol;
    }

    /**
     * Returns Is Suffix.
     * Currency format (is the symbol after the value)
     */
    public function getIsSuffix(): bool
    {
        return $this->isSuffix;
    }

    /**
     * Sets Is Suffix.
     * Currency format (is the symbol after the value)
     *
     * @required
     * @maps isSuffix
     */
    public function setIsSuffix(bool $isSuffix): void
    {
        $this->isSuffix = $isSuffix;
    }

    /**
     * Returns Has Space.
     * Currency format (is there a space between the symbol and the value)
     */
    public function getHasSpace(): bool
    {
        return $this->hasSpace;
    }

    /**
     * Sets Has Space.
     * Currency format (is there a space between the symbol and the value)
     *
     * @required
     * @maps hasSpace
     */
    public function setHasSpace(bool $hasSpace): void
    {
        $this->hasSpace = $hasSpace;
    }

    /**
     * Converts the CurrencyData object to a human-readable string representation.
     *
     * @return string The string representation of the CurrencyData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CurrencyData',
            [
                'code' => $this->code,
                'symbol' => $this->symbol,
                'isSuffix' => $this->isSuffix,
                'hasSpace' => $this->hasSpace,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['code', 'symbol', 'isSuffix', 'hasSpace'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['code']     = $this->code;
        $json['symbol']   = $this->symbol;
        $json['isSuffix'] = $this->isSuffix;
        $json['hasSpace'] = $this->hasSpace;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
