<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class ErrorPresenter implements \JsonSerializable
{
    /**
     * @var string
     */
    private $appErrorCode;

    /**
     * @var string
     */
    private $message;

    /**
     * @var array
     */
    private $reason = [];

    /**
     * @var array
     */
    private $subject = [];

    /**
     * @var array
     */
    private $subjectType = [];

    /**
     * @var array
     */
    private $type = [];

    /**
     * @param string $appErrorCode
     * @param string $message
     */
    public function __construct(string $appErrorCode, string $message)
    {
        $this->appErrorCode = $appErrorCode;
        $this->message = $message;
    }

    /**
     * Returns App Error Code.
     * custom error code for developer or user
     * Note: One of the following values will be returned:
     * 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1010, 1011, 1012, 1014, 1015, 1016
     */
    public function getAppErrorCode(): string
    {
        return $this->appErrorCode;
    }

    /**
     * Sets App Error Code.
     * custom error code for developer or user
     * Note: One of the following values will be returned:
     * 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1010, 1011, 1012, 1014, 1015, 1016
     *
     * @required
     * @maps appErrorCode
     */
    public function setAppErrorCode(string $appErrorCode): void
    {
        $this->appErrorCode = $appErrorCode;
    }

    /**
     * Returns Message.
     * Custom error message <br>
     * Note: One of the following values will be returned:
     * - Offer does not exist
     * - Customer does not exist
     * - Valid from date is invalid
     * - ValidityPeriod is invalid
     * - Offer is by default assigned to all customers, which cannot be changed.
     * - Assignment is not allowed
     * - Customer assign should have validity dates.
     * - Customer assign validity start date should be before the validity end date.
     * - Customer assign validity dates must be between the offer assignable dates.
     * - Offer validity start date should not be in the past.
     * - Customer already assigned to this offer.
     * - Offer module is disabled
     * - Partner code is not valid for this offer
     * - Reference ID already used
     * - Partner assignment already ended for this customer
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * Custom error message <br>
     * Note: One of the following values will be returned:
     * - Offer does not exist
     * - Customer does not exist
     * - Valid from date is invalid
     * - ValidityPeriod is invalid
     * - Offer is by default assigned to all customers, which cannot be changed.
     * - Assignment is not allowed
     * - Customer assign should have validity dates.
     * - Customer assign validity start date should be before the validity end date.
     * - Customer assign validity dates must be between the offer assignable dates.
     * - Offer validity start date should not be in the past.
     * - Customer already assigned to this offer.
     * - Offer module is disabled
     * - Partner code is not valid for this offer
     * - Reference ID already used
     * - Partner assignment already ended for this customer
     *
     * @required
     * @maps message
     */
    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Reason.
     * reason for the error
     */
    public function getReason(): ?string
    {
        if (count($this->reason) == 0) {
            return null;
        }
        return $this->reason['value'];
    }

    /**
     * Sets Reason.
     * reason for the error
     *
     * @maps reason
     */
    public function setReason(?string $reason): void
    {
        $this->reason['value'] = $reason;
    }

    /**
     * Unsets Reason.
     * reason for the error
     */
    public function unsetReason(): void
    {
        $this->reason = [];
    }

    /**
     * Returns Subject.
     * subject of the error. Examples will be shared later
     */
    public function getSubject(): ?string
    {
        if (count($this->subject) == 0) {
            return null;
        }
        return $this->subject['value'];
    }

    /**
     * Sets Subject.
     * subject of the error. Examples will be shared later
     *
     * @maps subject
     */
    public function setSubject(?string $subject): void
    {
        $this->subject['value'] = $subject;
    }

    /**
     * Unsets Subject.
     * subject of the error. Examples will be shared later
     */
    public function unsetSubject(): void
    {
        $this->subject = [];
    }

    /**
     * Returns Subject Type.
     * subject type of the error. Examples will be shared later.
     */
    public function getSubjectType(): ?string
    {
        if (count($this->subjectType) == 0) {
            return null;
        }
        return $this->subjectType['value'];
    }

    /**
     * Sets Subject Type.
     * subject type of the error. Examples will be shared later.
     *
     * @maps subjectType
     */
    public function setSubjectType(?string $subjectType): void
    {
        $this->subjectType['value'] = $subjectType;
    }

    /**
     * Unsets Subject Type.
     * subject type of the error. Examples will be shared later.
     */
    public function unsetSubjectType(): void
    {
        $this->subjectType = [];
    }

    /**
     * Returns Type.
     * Type of error. Examples will be shared later.
     */
    public function getType(): ?string
    {
        if (count($this->type) == 0) {
            return null;
        }
        return $this->type['value'];
    }

    /**
     * Sets Type.
     * Type of error. Examples will be shared later.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type['value'] = $type;
    }

    /**
     * Unsets Type.
     * Type of error. Examples will be shared later.
     */
    public function unsetType(): void
    {
        $this->type = [];
    }

    /**
     * Converts the ErrorPresenter object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorPresenter object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorPresenter',
            [
                'appErrorCode' => $this->appErrorCode,
                'message' => $this->message,
                'reason' => $this->getReason(),
                'subject' => $this->getSubject(),
                'subjectType' => $this->getSubjectType(),
                'type' => $this->getType(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['appErrorCode', 'message', 'reason', 'subject', 'subjectType', 'type'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['appErrorCode']    = $this->appErrorCode;
        $json['message']         = $this->message;
        if (!empty($this->reason)) {
            $json['reason']      = $this->reason['value'];
        }
        if (!empty($this->subject)) {
            $json['subject']     = $this->subject['value'];
        }
        if (!empty($this->subjectType)) {
            $json['subjectType'] = $this->subjectType['value'];
        }
        if (!empty($this->type)) {
            $json['type']        = $this->type['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
