<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class ErrorItem implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $title;

    /**
     * @var ErrorSource|null
     */
    private $source;

    /**
     * @var string|null
     */
    private $detail;

    /**
     * Returns Status.
     */
    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?int $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Title.
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Source.
     */
    public function getSource(): ?ErrorSource
    {
        return $this->source;
    }

    /**
     * Sets Source.
     *
     * @maps source
     */
    public function setSource(?ErrorSource $source): void
    {
        $this->source = $source;
    }

    /**
     * Returns Detail.
     */
    public function getDetail(): ?string
    {
        return $this->detail;
    }

    /**
     * Sets Detail.
     *
     * @maps detail
     */
    public function setDetail(?string $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * Converts the ErrorItem object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorItem',
            [
                'status' => $this->status,
                'title' => $this->title,
                'source' => $this->source,
                'detail' => $this->detail,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['status', 'title', 'source', 'detail'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->status)) {
            $json['status'] = $this->status;
        }
        if (isset($this->title)) {
            $json['title']  = $this->title;
        }
        if (isset($this->source)) {
            $json['source'] = $this->source;
        }
        if (isset($this->detail)) {
            $json['detail'] = $this->detail;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
