<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class ErrorBaseContainer implements \JsonSerializable
{
    /**
     * @var ErrorPresenter
     */
    private $user;

    /**
     * @var ErrorPresenter
     */
    private $developer;

    /**
     * @param ErrorPresenter $user
     * @param ErrorPresenter $developer
     */
    public function __construct(ErrorPresenter $user, ErrorPresenter $developer)
    {
        $this->user = $user;
        $this->developer = $developer;
    }

    /**
     * Returns User.
     */
    public function getUser(): ErrorPresenter
    {
        return $this->user;
    }

    /**
     * Sets User.
     *
     * @required
     * @maps User
     */
    public function setUser(ErrorPresenter $user): void
    {
        $this->user = $user;
    }

    /**
     * Returns Developer.
     */
    public function getDeveloper(): ErrorPresenter
    {
        return $this->developer;
    }

    /**
     * Sets Developer.
     *
     * @required
     * @maps Developer
     */
    public function setDeveloper(ErrorPresenter $developer): void
    {
        $this->developer = $developer;
    }

    /**
     * Converts the ErrorBaseContainer object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorBaseContainer object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorBaseContainer',
            [
                'user' => $this->user,
                'developer' => $this->developer,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['User', 'Developer'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['User']      = $this->user;
        $json['Developer'] = $this->developer;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
