<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use LoyaltyApIsLib\Utils\DateTimeHelper;
use stdClass;

class EvChargingDetails implements \JsonSerializable
{
    /**
     * @var string
     */
    private $chargePointSerialId;

    /**
     * @var string|null
     */
    private $chargePointConnectorTypeCd;

    /**
     * @var string|null
     */
    private $chargePointConnectorTypeDesc;

    /**
     * @var \DateTime
     */
    private $startDateTime;

    /**
     * @var \DateTime
     */
    private $endDateTime;

    /**
     * @var int
     */
    private $duration;

    /**
     * @param string $chargePointSerialId
     * @param \DateTime $startDateTime
     * @param \DateTime $endDateTime
     * @param int $duration
     */
    public function __construct(
        string $chargePointSerialId,
        \DateTime $startDateTime,
        \DateTime $endDateTime,
        int $duration
    ) {
        $this->chargePointSerialId = $chargePointSerialId;
        $this->startDateTime = $startDateTime;
        $this->endDateTime = $endDateTime;
        $this->duration = $duration;
    }

    /**
     * Returns Charge Point Serial Id.
     * Charging point serial ID
     */
    public function getChargePointSerialId(): string
    {
        return $this->chargePointSerialId;
    }

    /**
     * Sets Charge Point Serial Id.
     * Charging point serial ID
     *
     * @required
     * @maps chargePointSerialId
     */
    public function setChargePointSerialId(string $chargePointSerialId): void
    {
        $this->chargePointSerialId = $chargePointSerialId;
    }

    /**
     * Returns Charge Point Connector Type Cd.
     * Charging point connector type
     */
    public function getChargePointConnectorTypeCd(): ?string
    {
        return $this->chargePointConnectorTypeCd;
    }

    /**
     * Sets Charge Point Connector Type Cd.
     * Charging point connector type
     *
     * @maps chargePointConnectorTypeCd
     */
    public function setChargePointConnectorTypeCd(?string $chargePointConnectorTypeCd): void
    {
        $this->chargePointConnectorTypeCd = $chargePointConnectorTypeCd;
    }

    /**
     * Returns Charge Point Connector Type Desc.
     * Charging point connector description
     */
    public function getChargePointConnectorTypeDesc(): ?string
    {
        return $this->chargePointConnectorTypeDesc;
    }

    /**
     * Sets Charge Point Connector Type Desc.
     * Charging point connector description
     *
     * @maps chargePointConnectorTypeDesc
     */
    public function setChargePointConnectorTypeDesc(?string $chargePointConnectorTypeDesc): void
    {
        $this->chargePointConnectorTypeDesc = $chargePointConnectorTypeDesc;
    }

    /**
     * Returns Start Date Time.
     * Date and time at which the transaction started. Format as per ISO 8601 standard.
     */
    public function getStartDateTime(): \DateTime
    {
        return $this->startDateTime;
    }

    /**
     * Sets Start Date Time.
     * Date and time at which the transaction started. Format as per ISO 8601 standard.
     *
     * @required
     * @maps startDateTime
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setStartDateTime(\DateTime $startDateTime): void
    {
        $this->startDateTime = $startDateTime;
    }

    /**
     * Returns End Date Time.
     * Date and time at which the transaction ended. Format as per ISO 8601 standard.
     */
    public function getEndDateTime(): \DateTime
    {
        return $this->endDateTime;
    }

    /**
     * Sets End Date Time.
     * Date and time at which the transaction ended. Format as per ISO 8601 standard.
     *
     * @required
     * @maps endDateTime
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setEndDateTime(\DateTime $endDateTime): void
    {
        $this->endDateTime = $endDateTime;
    }

    /**
     * Returns Duration.
     * Duration of the transaction in seconds.
     */
    public function getDuration(): int
    {
        return $this->duration;
    }

    /**
     * Sets Duration.
     * Duration of the transaction in seconds.
     *
     * @required
     * @maps duration
     */
    public function setDuration(int $duration): void
    {
        $this->duration = $duration;
    }

    /**
     * Converts the EvChargingDetails object to a human-readable string representation.
     *
     * @return string The string representation of the EvChargingDetails object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EvChargingDetails',
            [
                'chargePointSerialId' => $this->chargePointSerialId,
                'chargePointConnectorTypeCd' => $this->chargePointConnectorTypeCd,
                'chargePointConnectorTypeDesc' => $this->chargePointConnectorTypeDesc,
                'startDateTime' => $this->startDateTime,
                'endDateTime' => $this->endDateTime,
                'duration' => $this->duration,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'chargePointSerialId',
        'chargePointConnectorTypeCd',
        'chargePointConnectorTypeDesc',
        'startDateTime',
        'endDateTime',
        'duration'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['chargePointSerialId']              = $this->chargePointSerialId;
        if (isset($this->chargePointConnectorTypeCd)) {
            $json['chargePointConnectorTypeCd']   = $this->chargePointConnectorTypeCd;
        }
        if (isset($this->chargePointConnectorTypeDesc)) {
            $json['chargePointConnectorTypeDesc'] = $this->chargePointConnectorTypeDesc;
        }
        $json['startDateTime']                    = DateTimeHelper::toRfc3339DateTime($this->startDateTime);
        $json['endDateTime']                      = DateTimeHelper::toRfc3339DateTime($this->endDateTime);
        $json['duration']                         = $this->duration;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
