<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class LoyaltyCardInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $loyaltyCard;

    /**
     * Returns Loyalty Card.
     * Loyalty card of the transaction.
     */
    public function getLoyaltyCard(): ?string
    {
        return $this->loyaltyCard;
    }

    /**
     * Sets Loyalty Card.
     * Loyalty card of the transaction.
     *
     * @maps loyaltyCard
     */
    public function setLoyaltyCard(?string $loyaltyCard): void
    {
        $this->loyaltyCard = $loyaltyCard;
    }

    /**
     * Converts the LoyaltyCardInfo object to a human-readable string representation.
     *
     * @return string The string representation of the LoyaltyCardInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'LoyaltyCardInfo',
            ['loyaltyCard' => $this->loyaltyCard, 'additionalProperties' => $this->additionalProperties]
        );
    }

    protected $propertyNames = ['loyaltyCard'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->loyaltyCard)) {
            $json['loyaltyCard'] = $this->loyaltyCard;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
