<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class M200UserPartners implements \JsonSerializable
{
    /**
     * @var string
     */
    private $uuid;

    /**
     * @var string
     */
    private $userStatus;

    /**
     * @var array
     */
    private $market;

    /**
     * @var string
     */
    private $accessToken;

    /**
     * @var string
     */
    private $refreshToken;

    /**
     * @param string $uuid
     * @param string $userStatus
     * @param array $market
     * @param string $accessToken
     * @param string $refreshToken
     */
    public function __construct(
        string $uuid,
        string $userStatus,
        array $market,
        string $accessToken,
        string $refreshToken
    ) {
        $this->uuid = $uuid;
        $this->userStatus = $userStatus;
        $this->market = $market;
        $this->accessToken = $accessToken;
        $this->refreshToken = $refreshToken;
    }

    /**
     * Returns Uuid.
     */
    public function getUuid(): string
    {
        return $this->uuid;
    }

    /**
     * Sets Uuid.
     *
     * @required
     * @maps uuid
     */
    public function setUuid(string $uuid): void
    {
        $this->uuid = $uuid;
    }

    /**
     * Returns User Status.
     */
    public function getUserStatus(): string
    {
        return $this->userStatus;
    }

    /**
     * Sets User Status.
     *
     * @required
     * @maps userStatus
     */
    public function setUserStatus(string $userStatus): void
    {
        $this->userStatus = $userStatus;
    }

    /**
     * Returns Market.
     */
    public function getMarket(): array
    {
        return $this->market;
    }

    /**
     * Sets Market.
     *
     * @required
     * @maps market
     */
    public function setMarket(array $market): void
    {
        $this->market = $market;
    }

    /**
     * Returns Access Token.
     */
    public function getAccessToken(): string
    {
        return $this->accessToken;
    }

    /**
     * Sets Access Token.
     *
     * @required
     * @maps accessToken
     */
    public function setAccessToken(string $accessToken): void
    {
        $this->accessToken = $accessToken;
    }

    /**
     * Returns Refresh Token.
     */
    public function getRefreshToken(): string
    {
        return $this->refreshToken;
    }

    /**
     * Sets Refresh Token.
     *
     * @required
     * @maps refreshToken
     */
    public function setRefreshToken(string $refreshToken): void
    {
        $this->refreshToken = $refreshToken;
    }

    /**
     * Converts the M200UserPartners object to a human-readable string representation.
     *
     * @return string The string representation of the M200UserPartners object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'M200UserPartners',
            [
                'uuid' => $this->uuid,
                'userStatus' => $this->userStatus,
                'market' => $this->market,
                'accessToken' => $this->accessToken,
                'refreshToken' => $this->refreshToken,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['uuid', 'userStatus', 'market', 'accessToken', 'refreshToken'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['uuid']         = $this->uuid;
        $json['userStatus']   = $this->userStatus;
        $json['market']       = $this->market;
        $json['accessToken']  = $this->accessToken;
        $json['refreshToken'] = $this->refreshToken;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
