<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class NotFoundErrorResponse implements \JsonSerializable
{
    /**
     * @var float
     */
    private $errorCode;

    /**
     * @var string
     */
    private $message;

    /**
     * @var ErrorInfo
     */
    private $error;

    /**
     * @param float $errorCode
     * @param string $message
     * @param ErrorInfo $error
     */
    public function __construct(float $errorCode, string $message, ErrorInfo $error)
    {
        $this->errorCode = $errorCode;
        $this->message = $message;
        $this->error = $error;
    }

    /**
     * Returns Error Code.
     * HTTP error code 404
     */
    public function getErrorCode(): float
    {
        return $this->errorCode;
    }

    /**
     * Sets Error Code.
     * HTTP error code 404
     *
     * @required
     * @maps errorCode
     */
    public function setErrorCode(float $errorCode): void
    {
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Message.
     * HTTP error message - Not Found
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * HTTP error message - Not Found
     *
     * @required
     * @maps message
     */
    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Error.
     */
    public function getError(): ErrorInfo
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @required
     * @maps error
     */
    public function setError(ErrorInfo $error): void
    {
        $this->error = $error;
    }

    /**
     * Converts the NotFoundErrorResponse object to a human-readable string representation.
     *
     * @return string The string representation of the NotFoundErrorResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'NotFoundErrorResponse',
            [
                'errorCode' => $this->errorCode,
                'message' => $this->message,
                'error' => $this->error,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['errorCode', 'message', 'error'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['errorCode'] = $this->errorCode;
        $json['message']   = $this->message;
        $json['error']     = $this->error;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
