<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class OfferInfo implements \JsonSerializable
{
    /**
     * @var float
     */
    private $discountValue;

    /**
     * @var int|null
     */
    private $loyaltyOfferAmount;

    /**
     * @var string|null
     */
    private $loyaltyOfferCode;

    /**
     * @var string|null
     */
    private $loyaltyOfferDescription;

    /**
     * @var string
     */
    private $loyaltyOfferId;

    /**
     * @var string|null
     */
    private $loyaltyOfferType;

    /**
     * @var string|null
     */
    private $loyaltySchemeCode;

    /**
     * @var string
     */
    private $reason;

    /**
     * @param float $discountValue
     * @param string $loyaltyOfferId
     * @param string $reason
     */
    public function __construct(float $discountValue, string $loyaltyOfferId, string $reason)
    {
        $this->discountValue = $discountValue;
        $this->loyaltyOfferId = $loyaltyOfferId;
        $this->reason = $reason;
    }

    /**
     * Returns Discount Value.
     * Discount value of the offer
     */
    public function getDiscountValue(): float
    {
        return $this->discountValue;
    }

    /**
     * Sets Discount Value.
     * Discount value of the offer
     *
     * @required
     * @maps discountValue
     */
    public function setDiscountValue(float $discountValue): void
    {
        $this->discountValue = $discountValue;
    }

    /**
     * Returns Loyalty Offer Amount.
     * Total amount of points awarded for the given product code.
     */
    public function getLoyaltyOfferAmount(): ?int
    {
        return $this->loyaltyOfferAmount;
    }

    /**
     * Sets Loyalty Offer Amount.
     * Total amount of points awarded for the given product code.
     *
     * @maps loyaltyOfferAmount
     */
    public function setLoyaltyOfferAmount(?int $loyaltyOfferAmount): void
    {
        $this->loyaltyOfferAmount = $loyaltyOfferAmount;
    }

    /**
     * Returns Loyalty Offer Code.
     * Unique ID of the voucher/coupon.
     */
    public function getLoyaltyOfferCode(): ?string
    {
        return $this->loyaltyOfferCode;
    }

    /**
     * Sets Loyalty Offer Code.
     * Unique ID of the voucher/coupon.
     *
     * @maps loyaltyOfferCode
     */
    public function setLoyaltyOfferCode(?string $loyaltyOfferCode): void
    {
        $this->loyaltyOfferCode = $loyaltyOfferCode;
    }

    /**
     * Returns Loyalty Offer Description.
     * Name of loyalty offer
     */
    public function getLoyaltyOfferDescription(): ?string
    {
        return $this->loyaltyOfferDescription;
    }

    /**
     * Sets Loyalty Offer Description.
     * Name of loyalty offer
     *
     * @maps loyaltyOfferDescription
     */
    public function setLoyaltyOfferDescription(?string $loyaltyOfferDescription): void
    {
        $this->loyaltyOfferDescription = $loyaltyOfferDescription;
    }

    /**
     * Returns Loyalty Offer Id.
     * Loyalty Offer ID
     */
    public function getLoyaltyOfferId(): string
    {
        return $this->loyaltyOfferId;
    }

    /**
     * Sets Loyalty Offer Id.
     * Loyalty Offer ID
     *
     * @required
     * @maps loyaltyOfferID
     */
    public function setLoyaltyOfferId(string $loyaltyOfferId): void
    {
        $this->loyaltyOfferId = $loyaltyOfferId;
    }

    /**
     * Returns Loyalty Offer Type.
     * Loyalty offer type
     */
    public function getLoyaltyOfferType(): ?string
    {
        return $this->loyaltyOfferType;
    }

    /**
     * Sets Loyalty Offer Type.
     * Loyalty offer type
     *
     * @maps loyaltyOfferType
     */
    public function setLoyaltyOfferType(?string $loyaltyOfferType): void
    {
        $this->loyaltyOfferType = $loyaltyOfferType;
    }

    /**
     * Returns Loyalty Scheme Code.
     * Loyalty Scheme code
     */
    public function getLoyaltySchemeCode(): ?string
    {
        return $this->loyaltySchemeCode;
    }

    /**
     * Sets Loyalty Scheme Code.
     * Loyalty Scheme code
     *
     * @maps loyaltySchemeCode
     */
    public function setLoyaltySchemeCode(?string $loyaltySchemeCode): void
    {
        $this->loyaltySchemeCode = $loyaltySchemeCode;
    }

    /**
     * Returns Reason.
     * Offer/reward name
     */
    public function getReason(): string
    {
        return $this->reason;
    }

    /**
     * Sets Reason.
     * Offer/reward name
     *
     * @required
     * @maps reason
     */
    public function setReason(string $reason): void
    {
        $this->reason = $reason;
    }

    /**
     * Converts the OfferInfo object to a human-readable string representation.
     *
     * @return string The string representation of the OfferInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OfferInfo',
            [
                'discountValue' => $this->discountValue,
                'loyaltyOfferAmount' => $this->loyaltyOfferAmount,
                'loyaltyOfferCode' => $this->loyaltyOfferCode,
                'loyaltyOfferDescription' => $this->loyaltyOfferDescription,
                'loyaltyOfferId' => $this->loyaltyOfferId,
                'loyaltyOfferType' => $this->loyaltyOfferType,
                'loyaltySchemeCode' => $this->loyaltySchemeCode,
                'reason' => $this->reason,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'discountValue',
        'loyaltyOfferAmount',
        'loyaltyOfferCode',
        'loyaltyOfferDescription',
        'loyaltyOfferID',
        'loyaltyOfferType',
        'loyaltySchemeCode',
        'reason'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['discountValue']               = $this->discountValue;
        if (isset($this->loyaltyOfferAmount)) {
            $json['loyaltyOfferAmount']      = $this->loyaltyOfferAmount;
        }
        if (isset($this->loyaltyOfferCode)) {
            $json['loyaltyOfferCode']        = $this->loyaltyOfferCode;
        }
        if (isset($this->loyaltyOfferDescription)) {
            $json['loyaltyOfferDescription'] = $this->loyaltyOfferDescription;
        }
        $json['loyaltyOfferID']              = $this->loyaltyOfferId;
        if (isset($this->loyaltyOfferType)) {
            $json['loyaltyOfferType']        = $this->loyaltyOfferType;
        }
        if (isset($this->loyaltySchemeCode)) {
            $json['loyaltySchemeCode']       = $this->loyaltySchemeCode;
        }
        $json['reason']                      = $this->reason;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
