<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use LoyaltyApIsLib\Utils\DateTimeHelper;
use stdClass;

class Offer implements \JsonSerializable
{
    /**
     * @var int
     */
    private $offerId;

    /**
     * @var string
     */
    private $referenceId;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $description;

    /**
     * @var \DateTime
     */
    private $validFrom;

    /**
     * @var array
     */
    private $validTo = [];

    /**
     * @param int $offerId
     * @param string $referenceId
     * @param string $title
     * @param string $description
     * @param \DateTime $validFrom
     */
    public function __construct(
        int $offerId,
        string $referenceId,
        string $title,
        string $description,
        \DateTime $validFrom
    ) {
        $this->offerId = $offerId;
        $this->referenceId = $referenceId;
        $this->title = $title;
        $this->description = $description;
        $this->validFrom = $validFrom;
    }

    /**
     * Returns Offer Id.
     * Offer ID provided upon offer configuration
     */
    public function getOfferId(): int
    {
        return $this->offerId;
    }

    /**
     * Sets Offer Id.
     * Offer ID provided upon offer configuration
     *
     * @required
     * @maps offerId
     */
    public function setOfferId(int $offerId): void
    {
        $this->offerId = $offerId;
    }

    /**
     * Returns Reference Id.
     * Unique Reference ID for the transaction from the partner. Used to identify duplicate requests.
     */
    public function getReferenceId(): string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     * Unique Reference ID for the transaction from the partner. Used to identify duplicate requests.
     *
     * @required
     * @maps referenceId
     */
    public function setReferenceId(string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Returns Title.
     * Title of the partner's offer, given upon configuration
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     * Title of the partner's offer, given upon configuration
     *
     * @required
     * @maps title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Description.
     * Description of the partner's offer, set up upon offer configuration
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description of the partner's offer, set up upon offer configuration
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Valid From.
     * Offer validity start date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     */
    public function getValidFrom(): \DateTime
    {
        return $this->validFrom;
    }

    /**
     * Sets Valid From.
     * Offer validity start date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     *
     * @required
     * @maps validFrom
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setValidFrom(\DateTime $validFrom): void
    {
        $this->validFrom = $validFrom;
    }

    /**
     * Returns Valid To.
     * Offer validity end date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     *
     * Nullable field value, in case of the offer has infinite valid to.
     */
    public function getValidTo(): ?\DateTime
    {
        if (count($this->validTo) == 0) {
            return null;
        }
        return $this->validTo['value'];
    }

    /**
     * Sets Valid To.
     * Offer validity end date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     *
     * Nullable field value, in case of the offer has infinite valid to.
     *
     * @maps validTo
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setValidTo(?\DateTime $validTo): void
    {
        $this->validTo['value'] = $validTo;
    }

    /**
     * Unsets Valid To.
     * Offer validity end date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     *
     * Nullable field value, in case of the offer has infinite valid to.
     */
    public function unsetValidTo(): void
    {
        $this->validTo = [];
    }

    /**
     * Converts the Offer object to a human-readable string representation.
     *
     * @return string The string representation of the Offer object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Offer',
            [
                'offerId' => $this->offerId,
                'referenceId' => $this->referenceId,
                'title' => $this->title,
                'description' => $this->description,
                'validFrom' => $this->validFrom,
                'validTo' => $this->getValidTo(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['offerId', 'referenceId', 'title', 'description', 'validFrom', 'validTo'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['offerId']     = $this->offerId;
        $json['referenceId'] = $this->referenceId;
        $json['title']       = $this->title;
        $json['description'] = $this->description;
        $json['validFrom']   = DateTimeHelper::toRfc3339DateTime($this->validFrom);
        if (!empty($this->validTo)) {
            $json['validTo'] = DateTimeHelper::toRfc3339DateTime($this->validTo['value']);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
