<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use LoyaltyApIsLib\Utils\DateTimeHelper;
use stdClass;

class OfferAssignment implements \JsonSerializable
{
    /**
     * @var string
     */
    private $referenceId;

    /**
     * @var string
     */
    private $consumerUuid;

    /**
     * @var string
     */
    private $offerId;

    /**
     * @var \DateTime|null
     */
    private $validFrom;

    /**
     * @var float|null
     */
    private $validityPeriod;

    /**
     * @var array
     */
    private $validTo = [];

    /**
     * @param string $referenceId
     * @param string $consumerUuid
     * @param string $offerId
     */
    public function __construct(string $referenceId, string $consumerUuid, string $offerId)
    {
        $this->referenceId = $referenceId;
        $this->consumerUuid = $consumerUuid;
        $this->offerId = $offerId;
    }

    /**
     * Returns Reference Id.
     * Unique Reference ID for the transaction from the partner. Used to identify duplicate requests.
     */
    public function getReferenceId(): string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     * Unique Reference ID for the transaction from the partner. Used to identify duplicate requests.
     *
     * @required
     * @maps referenceId
     */
    public function setReferenceId(string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Returns Consumer Uuid.
     * SSO uuid of the user signed in with Shell credentials
     * Format: 32 hexadecimal digits grouped the following way: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
     */
    public function getConsumerUuid(): string
    {
        return $this->consumerUuid;
    }

    /**
     * Sets Consumer Uuid.
     * SSO uuid of the user signed in with Shell credentials
     * Format: 32 hexadecimal digits grouped the following way: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
     *
     * @required
     * @maps consumerUuid
     */
    public function setConsumerUuid(string $consumerUuid): void
    {
        $this->consumerUuid = $consumerUuid;
    }

    /**
     * Returns Offer Id.
     * Offer identifier shared by Shell.
     * Format: string(30)
     */
    public function getOfferId(): string
    {
        return $this->offerId;
    }

    /**
     * Sets Offer Id.
     * Offer identifier shared by Shell.
     * Format: string(30)
     *
     * @required
     * @maps offerId
     */
    public function setOfferId(string $offerId): void
    {
        $this->offerId = $offerId;
    }

    /**
     * Returns Valid From.
     * Offer validity start date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     *
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     */
    public function getValidFrom(): ?\DateTime
    {
        return $this->validFrom;
    }

    /**
     * Sets Valid From.
     * Offer validity start date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     *
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     *
     * @maps validFrom
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setValidFrom(?\DateTime $validFrom): void
    {
        $this->validFrom = $validFrom;
    }

    /**
     * Returns Validity Period.
     * Offer validity period (Number of days)
     * If validityPeriod is greater than zero, validTo will be ignored.
     * The offer will be valid till:
     * validfrom + validityperiod
     * If the resulting valid to date would be during the day, then its validity is modified to last until
     * midnight in the timezone of the validFrom date.
     * E.g. If valiFrom is "2021-03-08T17:12:55Z+01:00" (Central European time) and validtyPeriod is 3
     * then the offer will be valid till "2021-03-11T23:59:59Z+01:00" (Central European Time)
     */
    public function getValidityPeriod(): ?float
    {
        return $this->validityPeriod;
    }

    /**
     * Sets Validity Period.
     * Offer validity period (Number of days)
     * If validityPeriod is greater than zero, validTo will be ignored.
     * The offer will be valid till:
     * validfrom + validityperiod
     * If the resulting valid to date would be during the day, then its validity is modified to last until
     * midnight in the timezone of the validFrom date.
     * E.g. If valiFrom is "2021-03-08T17:12:55Z+01:00" (Central European time) and validtyPeriod is 3
     * then the offer will be valid till "2021-03-11T23:59:59Z+01:00" (Central European Time)
     *
     * @maps validityPeriod
     */
    public function setValidityPeriod(?float $validityPeriod): void
    {
        $this->validityPeriod = $validityPeriod;
    }

    /**
     * Returns Valid To.
     * Offer validity end date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     * Field value is ignored if validityPeriod is bigger than zero.
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     */
    public function getValidTo(): ?\DateTime
    {
        if (count($this->validTo) == 0) {
            return null;
        }
        return $this->validTo['value'];
    }

    /**
     * Sets Valid To.
     * Offer validity end date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     * Field value is ignored if validityPeriod is bigger than zero.
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     *
     * @maps validTo
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setValidTo(?\DateTime $validTo): void
    {
        $this->validTo['value'] = $validTo;
    }

    /**
     * Unsets Valid To.
     * Offer validity end date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
     * Field value is ignored if validityPeriod is bigger than zero.
     *
     * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered
     * UTC.
     *
     * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets
     * describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC.
     * Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or
     * later) than UTC
     */
    public function unsetValidTo(): void
    {
        $this->validTo = [];
    }

    /**
     * Converts the OfferAssignment object to a human-readable string representation.
     *
     * @return string The string representation of the OfferAssignment object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OfferAssignment',
            [
                'referenceId' => $this->referenceId,
                'consumerUuid' => $this->consumerUuid,
                'offerId' => $this->offerId,
                'validFrom' => $this->validFrom,
                'validityPeriod' => $this->validityPeriod,
                'validTo' => $this->getValidTo(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['referenceId', 'consumerUuid', 'offerId', 'validFrom', 'validityPeriod', 'validTo'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['referenceId']        = $this->referenceId;
        $json['consumerUuid']       = $this->consumerUuid;
        $json['offerId']            = $this->offerId;
        if (isset($this->validFrom)) {
            $json['validFrom']      = DateTimeHelper::toRfc3339DateTime($this->validFrom);
        }
        if (isset($this->validityPeriod)) {
            $json['validityPeriod'] = $this->validityPeriod;
        }
        if (!empty($this->validTo)) {
            $json['validTo']        = DateTimeHelper::toRfc3339DateTime($this->validTo['value']);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
