<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class PointsToCash implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $pointsRedeemed;

    /**
     * @var float|null
     */
    private $totalAmount;

    /**
     * @var bool|null
     */
    private $pointsToCashMop;

    /**
     * Returns Points Redeemed.
     * The points used for converting it to cash
     */
    public function getPointsRedeemed(): ?float
    {
        return $this->pointsRedeemed;
    }

    /**
     * Sets Points Redeemed.
     * The points used for converting it to cash
     *
     * @maps pointsRedeemed
     */
    public function setPointsRedeemed(?float $pointsRedeemed): void
    {
        $this->pointsRedeemed = $pointsRedeemed;
    }

    /**
     * Returns Total Amount.
     * Total amount in cash used
     */
    public function getTotalAmount(): ?float
    {
        return $this->totalAmount;
    }

    /**
     * Sets Total Amount.
     * Total amount in cash used
     *
     * @maps totalAmount
     */
    public function setTotalAmount(?float $totalAmount): void
    {
        $this->totalAmount = $totalAmount;
    }

    /**
     * Returns Points to Cash Mop.
     * Indication if the p2c was used as a method of payment
     */
    public function getPointsToCashMop(): ?bool
    {
        return $this->pointsToCashMop;
    }

    /**
     * Sets Points to Cash Mop.
     * Indication if the p2c was used as a method of payment
     *
     * @maps pointsToCashMOP
     */
    public function setPointsToCashMop(?bool $pointsToCashMop): void
    {
        $this->pointsToCashMop = $pointsToCashMop;
    }

    /**
     * Converts the PointsToCash object to a human-readable string representation.
     *
     * @return string The string representation of the PointsToCash object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PointsToCash',
            [
                'pointsRedeemed' => $this->pointsRedeemed,
                'totalAmount' => $this->totalAmount,
                'pointsToCashMop' => $this->pointsToCashMop,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['pointsRedeemed', 'totalAmount', 'pointsToCashMOP'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->pointsRedeemed)) {
            $json['pointsRedeemed']  = $this->pointsRedeemed;
        }
        if (isset($this->totalAmount)) {
            $json['totalAmount']     = $this->totalAmount;
        }
        if (isset($this->pointsToCashMop)) {
            $json['pointsToCashMOP'] = $this->pointsToCashMop;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
