<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Indicating the Type of the product (Fuel, CR, CC, PARTNER, OTHER, GREEN_ENERGY).
 */
class ProductType
{
    public const FUEL = 'FUEL';

    public const CR = 'CR';

    public const CC = 'CC';

    public const PARTNER = 'PARTNER';

    public const OTHER = 'OTHER';

    public const GREEN_ENERGY = 'GREEN_ENERGY';

    private const _ALL_VALUES = [self::FUEL, self::CR, self::CC, self::PARTNER, self::OTHER, self::GREEN_ENERGY];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ProductType.");
    }
}
