<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class RedemptionResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $referenceId;

    /**
     * @var string
     */
    private $transactionDateTime;

    /**
     * @var string
     */
    private $updatedPointBalance;

    /**
     * @var RedemptionResponseItem[]
     */
    private $redemptionReqArray;

    /**
     * @param string $referenceId
     * @param string $transactionDateTime
     * @param string $updatedPointBalance
     * @param RedemptionResponseItem[] $redemptionReqArray
     */
    public function __construct(
        string $referenceId,
        string $transactionDateTime,
        string $updatedPointBalance,
        array $redemptionReqArray
    ) {
        $this->referenceId = $referenceId;
        $this->transactionDateTime = $transactionDateTime;
        $this->updatedPointBalance = $updatedPointBalance;
        $this->redemptionReqArray = $redemptionReqArray;
    }

    /**
     * Returns Reference Id.
     * A unique Reference ID for the transaction, generated by the partner.
     */
    public function getReferenceId(): string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     * A unique Reference ID for the transaction, generated by the partner.
     *
     * @required
     * @maps referenceId
     */
    public function setReferenceId(string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Returns Transaction Date Time.
     * The time and date of the redemption transaction.
     */
    public function getTransactionDateTime(): string
    {
        return $this->transactionDateTime;
    }

    /**
     * Sets Transaction Date Time.
     * The time and date of the redemption transaction.
     *
     * @required
     * @maps transactionDateTime
     */
    public function setTransactionDateTime(string $transactionDateTime): void
    {
        $this->transactionDateTime = $transactionDateTime;
    }

    /**
     * Returns Updated Point Balance.
     * The user's current loyalty point balance after the requested items have been redeemed.
     */
    public function getUpdatedPointBalance(): string
    {
        return $this->updatedPointBalance;
    }

    /**
     * Sets Updated Point Balance.
     * The user's current loyalty point balance after the requested items have been redeemed.
     *
     * @required
     * @maps updatedPointBalance
     */
    public function setUpdatedPointBalance(string $updatedPointBalance): void
    {
        $this->updatedPointBalance = $updatedPointBalance;
    }

    /**
     * Returns Redemption Req Array.
     * This array requests the points to be redeemed from the users point balance for the items requested.
     * The same information will be shown to the user. Multiple items can be redeemed in a single API
     * request.
     *
     * @return RedemptionResponseItem[]
     */
    public function getRedemptionReqArray(): array
    {
        return $this->redemptionReqArray;
    }

    /**
     * Sets Redemption Req Array.
     * This array requests the points to be redeemed from the users point balance for the items requested.
     * The same information will be shown to the user. Multiple items can be redeemed in a single API
     * request.
     *
     * @required
     * @maps redemptionReqArray
     *
     * @param RedemptionResponseItem[] $redemptionReqArray
     */
    public function setRedemptionReqArray(array $redemptionReqArray): void
    {
        $this->redemptionReqArray = $redemptionReqArray;
    }

    /**
     * Converts the RedemptionResponse object to a human-readable string representation.
     *
     * @return string The string representation of the RedemptionResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RedemptionResponse',
            [
                'referenceId' => $this->referenceId,
                'transactionDateTime' => $this->transactionDateTime,
                'updatedPointBalance' => $this->updatedPointBalance,
                'redemptionReqArray' => $this->redemptionReqArray,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['referenceId', 'transactionDateTime', 'updatedPointBalance', 'redemptionReqArray'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['referenceId']         = $this->referenceId;
        $json['transactionDateTime'] = $this->transactionDateTime;
        $json['updatedPointBalance'] = $this->updatedPointBalance;
        $json['redemptionReqArray']  = $this->redemptionReqArray;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
