<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class RedemptionResponseItem implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $itemId;

    /**
     * @var int|null
     */
    private $quantity;

    /**
     * @var int|null
     */
    private $points;

    /**
     * @var string|null
     */
    private $reasonForRedemption;

    /**
     * Returns Item Id.
     * Unique Item ID for the transaction from the partner. Used to identify the catalogue item in the
     * Shell Loyalty Platform. Each Partner will have one or more items set up in the Shell Loyalty
     * Platform.
     */
    public function getItemId(): ?string
    {
        return $this->itemId;
    }

    /**
     * Sets Item Id.
     * Unique Item ID for the transaction from the partner. Used to identify the catalogue item in the
     * Shell Loyalty Platform. Each Partner will have one or more items set up in the Shell Loyalty
     * Platform.
     *
     * @maps itemId
     */
    public function setItemId(?string $itemId): void
    {
        $this->itemId = $itemId;
    }

    /**
     * Returns Quantity.
     * The quantity of the items required.
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     * The quantity of the items required.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Points.
     * The number of points that will be redemmed from the Shell Loyalty Platform.
     */
    public function getPoints(): ?int
    {
        return $this->points;
    }

    /**
     * Sets Points.
     * The number of points that will be redemmed from the Shell Loyalty Platform.
     *
     * @maps points
     */
    public function setPoints(?int $points): void
    {
        $this->points = $points;
    }

    /**
     * Returns Reason for Redemption.
     * The reason for the points redemption. This attribute will be shown in the Transaction History feture.
     */
    public function getReasonForRedemption(): ?string
    {
        return $this->reasonForRedemption;
    }

    /**
     * Sets Reason for Redemption.
     * The reason for the points redemption. This attribute will be shown in the Transaction History feture.
     *
     * @maps reasonForRedemption
     */
    public function setReasonForRedemption(?string $reasonForRedemption): void
    {
        $this->reasonForRedemption = $reasonForRedemption;
    }

    /**
     * Converts the RedemptionResponseItem object to a human-readable string representation.
     *
     * @return string The string representation of the RedemptionResponseItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RedemptionResponseItem',
            [
                'itemId' => $this->itemId,
                'quantity' => $this->quantity,
                'points' => $this->points,
                'reasonForRedemption' => $this->reasonForRedemption,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['itemId', 'quantity', 'points', 'reasonForRedemption'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->itemId)) {
            $json['itemId']              = $this->itemId;
        }
        if (isset($this->quantity)) {
            $json['quantity']            = $this->quantity;
        }
        if (isset($this->points)) {
            $json['points']              = $this->points;
        }
        if (isset($this->reasonForRedemption)) {
            $json['reasonForRedemption'] = $this->reasonForRedemption;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
