<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class RedemptionRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $uuid;

    /**
     * @var string
     */
    private $referenceId;

    /**
     * @var RedemptionItem[]
     */
    private $redemptionReqArray;

    /**
     * @param string $uuid
     * @param string $referenceId
     * @param RedemptionItem[] $redemptionReqArray
     */
    public function __construct(string $uuid, string $referenceId, array $redemptionReqArray)
    {
        $this->uuid = $uuid;
        $this->referenceId = $referenceId;
        $this->redemptionReqArray = $redemptionReqArray;
    }

    /**
     * Returns Uuid.
     * The SSO uuid of the user signed in with Shell credentials.
     * Format: 32 hexadecimal digits grouped the following way: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
     * See: https://www.wikiwand.com/en/Universally_unique_identifier#/Format
     */
    public function getUuid(): string
    {
        return $this->uuid;
    }

    /**
     * Sets Uuid.
     * The SSO uuid of the user signed in with Shell credentials.
     * Format: 32 hexadecimal digits grouped the following way: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
     * See: https://www.wikiwand.com/en/Universally_unique_identifier#/Format
     *
     * @required
     * @maps uuid
     */
    public function setUuid(string $uuid): void
    {
        $this->uuid = $uuid;
    }

    /**
     * Returns Reference Id.
     * A unique ID for the transaction from the partner. Used to identify duplicate requests.
     */
    public function getReferenceId(): string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     * A unique ID for the transaction from the partner. Used to identify duplicate requests.
     *
     * @required
     * @maps referenceId
     */
    public function setReferenceId(string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Returns Redemption Req Array.
     * Specifies the number of points to be redeemed from the user's point balance and the reason for
     * redemption, which will also be shown to the user. Mutiple redemption items can be submitted in a
     * single API request.
     *
     * @return RedemptionItem[]
     */
    public function getRedemptionReqArray(): array
    {
        return $this->redemptionReqArray;
    }

    /**
     * Sets Redemption Req Array.
     * Specifies the number of points to be redeemed from the user's point balance and the reason for
     * redemption, which will also be shown to the user. Mutiple redemption items can be submitted in a
     * single API request.
     *
     * @required
     * @maps redemptionReqArray
     *
     * @param RedemptionItem[] $redemptionReqArray
     */
    public function setRedemptionReqArray(array $redemptionReqArray): void
    {
        $this->redemptionReqArray = $redemptionReqArray;
    }

    /**
     * Converts the RedemptionRequest object to a human-readable string representation.
     *
     * @return string The string representation of the RedemptionRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RedemptionRequest',
            [
                'uuid' => $this->uuid,
                'referenceId' => $this->referenceId,
                'redemptionReqArray' => $this->redemptionReqArray,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['uuid', 'referenceId', 'redemptionReqArray'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['uuid']               = $this->uuid;
        $json['referenceId']        = $this->referenceId;
        $json['redemptionReqArray'] = $this->redemptionReqArray;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
