<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class RedemptionItem implements \JsonSerializable
{
    /**
     * @var string
     */
    private $itemId;

    /**
     * @var int|null
     */
    private $quantity = 1;

    /**
     * @var int
     */
    private $points;

    /**
     * @var string
     */
    private $reasonForRedemption;

    /**
     * @param string $itemId
     * @param int $points
     * @param string $reasonForRedemption
     */
    public function __construct(string $itemId, int $points, string $reasonForRedemption)
    {
        $this->itemId = $itemId;
        $this->points = $points;
        $this->reasonForRedemption = $reasonForRedemption;
    }

    /**
     * Returns Item Id.
     * The itemID identifies the catalogue item in the loyalty system. Shell will set these up and share
     * the IDs with the partner.
     */
    public function getItemId(): string
    {
        return $this->itemId;
    }

    /**
     * Sets Item Id.
     * The itemID identifies the catalogue item in the loyalty system. Shell will set these up and share
     * the IDs with the partner.
     *
     * @required
     * @maps itemId
     */
    public function setItemId(string $itemId): void
    {
        $this->itemId = $itemId;
    }

    /**
     * Returns Quantity.
     * Number of items redeemed on the user's behalf. If the quantity is not specified, the system will
     * assume a default quantity of 1. This is not used for the calculation of points, but only for
     * displaying to the user.
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     * Number of items redeemed on the user's behalf. If the quantity is not specified, the system will
     * assume a default quantity of 1. This is not used for the calculation of points, but only for
     * displaying to the user.
     *
     * @maps quantity
     */
    public function setQuantity(?int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Points.
     * Total number of points to be redeemed from the Shell Loyalty Platform for this item.
     */
    public function getPoints(): int
    {
        return $this->points;
    }

    /**
     * Sets Points.
     * Total number of points to be redeemed from the Shell Loyalty Platform for this item.
     *
     * @required
     * @maps points
     */
    public function setPoints(int $points): void
    {
        $this->points = $points;
    }

    /**
     * Returns Reason for Redemption.
     * Reason for the points redemption. This attribute will be shown to the customer via app/web channel
     * under Transaction History.
     */
    public function getReasonForRedemption(): string
    {
        return $this->reasonForRedemption;
    }

    /**
     * Sets Reason for Redemption.
     * Reason for the points redemption. This attribute will be shown to the customer via app/web channel
     * under Transaction History.
     *
     * @required
     * @maps reasonForRedemption
     */
    public function setReasonForRedemption(string $reasonForRedemption): void
    {
        $this->reasonForRedemption = $reasonForRedemption;
    }

    /**
     * Converts the RedemptionItem object to a human-readable string representation.
     *
     * @return string The string representation of the RedemptionItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RedemptionItem',
            [
                'itemId' => $this->itemId,
                'quantity' => $this->quantity,
                'points' => $this->points,
                'reasonForRedemption' => $this->reasonForRedemption,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['itemId', 'quantity', 'points', 'reasonForRedemption'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['itemId']              = $this->itemId;
        if (isset($this->quantity)) {
            $json['quantity']        = $this->quantity;
        }
        $json['points']              = $this->points;
        $json['reasonForRedemption'] = $this->reasonForRedemption;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
