<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class SaleItem implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $description;

    /**
     * @var float
     */
    private $amount;

    /**
     * @var string
     */
    private $detailType;

    /**
     * @var float
     */
    private $discountAmount;

    /**
     * @var OfferInfo[]
     */
    private $offerInfos;

    /**
     * @var OfferLanguage|null
     */
    private $offerLang;

    /**
     * @var float
     */
    private $originalAmount;

    /**
     * @var float|null
     */
    private $originalNetAmount;

    /**
     * @var SaleItemProduct
     */
    private $productData;

    /**
     * @var float
     */
    private $quantity;

    /**
     * @var float|null
     */
    private $vatAmount;

    /**
     * @var float|null
     */
    private $vatRate;

    /**
     * @var VoucherItem[]|null
     */
    private $voucherItems;

    /**
     * @var string[]|null
     */
    private $vouchers;

    /**
     * @var float|null
     */
    private $unitPrice;

    /**
     * @var string|null
     */
    private $unitMeasure;

    /**
     * @var EvChargingDetails|null
     */
    private $ev;

    /**
     * @var int|null
     */
    private $points;

    /**
     * @param float $amount
     * @param string $detailType
     * @param float $discountAmount
     * @param OfferInfo[] $offerInfos
     * @param float $originalAmount
     * @param SaleItemProduct $productData
     * @param float $quantity
     */
    public function __construct(
        float $amount,
        string $detailType,
        float $discountAmount,
        array $offerInfos,
        float $originalAmount,
        SaleItemProduct $productData,
        float $quantity
    ) {
        $this->amount = $amount;
        $this->detailType = $detailType;
        $this->discountAmount = $discountAmount;
        $this->offerInfos = $offerInfos;
        $this->originalAmount = $originalAmount;
        $this->productData = $productData;
        $this->quantity = $quantity;
    }

    /**
     * Returns Description.
     * Description - currently not in use
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description - currently not in use
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Amount.
     * Total amount
     */
    public function getAmount(): float
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Total amount
     *
     * @required
     * @maps amount
     */
    public function setAmount(float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Detail Type.
     * Indicates the Type of the transaction detail row (award, redemption, transfer, voucher, refund or
     * central award).
     */
    public function getDetailType(): string
    {
        return $this->detailType;
    }

    /**
     * Sets Detail Type.
     * Indicates the Type of the transaction detail row (award, redemption, transfer, voucher, refund or
     * central award).
     *
     * @required
     * @maps detailType
     * @factory \LoyaltyApIsLib\Models\TransactionDetailType::checkValue
     */
    public function setDetailType(string $detailType): void
    {
        $this->detailType = $detailType;
    }

    /**
     * Returns Discount Amount.
     * Discount amount of sales line
     */
    public function getDiscountAmount(): float
    {
        return $this->discountAmount;
    }

    /**
     * Sets Discount Amount.
     * Discount amount of sales line
     *
     * @required
     * @maps discountAmount
     */
    public function setDiscountAmount(float $discountAmount): void
    {
        $this->discountAmount = $discountAmount;
    }

    /**
     * Returns Offer Infos.
     *
     * @return OfferInfo[]
     */
    public function getOfferInfos(): array
    {
        return $this->offerInfos;
    }

    /**
     * Sets Offer Infos.
     *
     * @required
     * @maps offerInfos
     *
     * @param OfferInfo[] $offerInfos
     */
    public function setOfferInfos(array $offerInfos): void
    {
        $this->offerInfos = $offerInfos;
    }

    /**
     * Returns Offer Lang.
     */
    public function getOfferLang(): ?OfferLanguage
    {
        return $this->offerLang;
    }

    /**
     * Sets Offer Lang.
     *
     * @maps offerLang
     */
    public function setOfferLang(?OfferLanguage $offerLang): void
    {
        $this->offerLang = $offerLang;
    }

    /**
     * Returns Original Amount.
     * Original amount of sales line
     */
    public function getOriginalAmount(): float
    {
        return $this->originalAmount;
    }

    /**
     * Sets Original Amount.
     * Original amount of sales line
     *
     * @required
     * @maps originalAmount
     */
    public function setOriginalAmount(float $originalAmount): void
    {
        $this->originalAmount = $originalAmount;
    }

    /**
     * Returns Original Net Amount.
     * Original amount excluding VAT
     */
    public function getOriginalNetAmount(): ?float
    {
        return $this->originalNetAmount;
    }

    /**
     * Sets Original Net Amount.
     * Original amount excluding VAT
     *
     * @maps originalNetAmount
     */
    public function setOriginalNetAmount(?float $originalNetAmount): void
    {
        $this->originalNetAmount = $originalNetAmount;
    }

    /**
     * Returns Product Data.
     */
    public function getProductData(): SaleItemProduct
    {
        return $this->productData;
    }

    /**
     * Sets Product Data.
     *
     * @required
     * @maps productData
     */
    public function setProductData(SaleItemProduct $productData): void
    {
        $this->productData = $productData;
    }

    /**
     * Returns Quantity.
     * Quantity of product
     */
    public function getQuantity(): float
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     * Quantity of product
     *
     * @required
     * @maps quantity
     */
    public function setQuantity(float $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Vat Amount.
     * Value added tax
     */
    public function getVatAmount(): ?float
    {
        return $this->vatAmount;
    }

    /**
     * Sets Vat Amount.
     * Value added tax
     *
     * @maps vatAmount
     */
    public function setVatAmount(?float $vatAmount): void
    {
        $this->vatAmount = $vatAmount;
    }

    /**
     * Returns Vat Rate.
     * VAT rate of sales line
     */
    public function getVatRate(): ?float
    {
        return $this->vatRate;
    }

    /**
     * Sets Vat Rate.
     * VAT rate of sales line
     *
     * @maps vatRate
     */
    public function setVatRate(?float $vatRate): void
    {
        $this->vatRate = $vatRate;
    }

    /**
     * Returns Voucher Items.
     *
     * @return VoucherItem[]|null
     */
    public function getVoucherItems(): ?array
    {
        return $this->voucherItems;
    }

    /**
     * Sets Voucher Items.
     *
     * @maps voucherItems
     *
     * @param VoucherItem[]|null $voucherItems
     */
    public function setVoucherItems(?array $voucherItems): void
    {
        $this->voucherItems = $voucherItems;
    }

    /**
     * Returns Vouchers.
     * List of vouchers
     *
     * @return string[]|null
     */
    public function getVouchers(): ?array
    {
        return $this->vouchers;
    }

    /**
     * Sets Vouchers.
     * List of vouchers
     *
     * @maps vouchers
     *
     * @param string[]|null $vouchers
     */
    public function setVouchers(?array $vouchers): void
    {
        $this->vouchers = $vouchers;
    }

    /**
     * Returns Unit Price.
     * Unit price of sale item
     */
    public function getUnitPrice(): ?float
    {
        return $this->unitPrice;
    }

    /**
     * Sets Unit Price.
     * Unit price of sale item
     *
     * @maps unitPrice
     */
    public function setUnitPrice(?float $unitPrice): void
    {
        $this->unitPrice = $unitPrice;
    }

    /**
     * Returns Unit Measure.
     * Unit of measure
     */
    public function getUnitMeasure(): ?string
    {
        return $this->unitMeasure;
    }

    /**
     * Sets Unit Measure.
     * Unit of measure
     *
     * @maps unitMeasure
     * @factory \LoyaltyApIsLib\Models\UnitMeasure::checkValue
     */
    public function setUnitMeasure(?string $unitMeasure): void
    {
        $this->unitMeasure = $unitMeasure;
    }

    /**
     * Returns Ev.
     */
    public function getEv(): ?EvChargingDetails
    {
        return $this->ev;
    }

    /**
     * Sets Ev.
     *
     * @maps EV
     */
    public function setEv(?EvChargingDetails $ev): void
    {
        $this->ev = $ev;
    }

    /**
     * Returns Points.
     * Points earned in a transaction
     */
    public function getPoints(): ?int
    {
        return $this->points;
    }

    /**
     * Sets Points.
     * Points earned in a transaction
     *
     * @maps points
     */
    public function setPoints(?int $points): void
    {
        $this->points = $points;
    }

    /**
     * Converts the SaleItem object to a human-readable string representation.
     *
     * @return string The string representation of the SaleItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SaleItem',
            [
                'description' => $this->description,
                'amount' => $this->amount,
                'detailType' => $this->detailType,
                'discountAmount' => $this->discountAmount,
                'offerInfos' => $this->offerInfos,
                'offerLang' => $this->offerLang,
                'originalAmount' => $this->originalAmount,
                'originalNetAmount' => $this->originalNetAmount,
                'productData' => $this->productData,
                'quantity' => $this->quantity,
                'vatAmount' => $this->vatAmount,
                'vatRate' => $this->vatRate,
                'voucherItems' => $this->voucherItems,
                'vouchers' => $this->vouchers,
                'unitPrice' => $this->unitPrice,
                'unitMeasure' => $this->unitMeasure,
                'ev' => $this->ev,
                'points' => $this->points,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'description',
        'amount',
        'detailType',
        'discountAmount',
        'offerInfos',
        'offerLang',
        'originalAmount',
        'originalNetAmount',
        'productData',
        'quantity',
        'vatAmount',
        'vatRate',
        'voucherItems',
        'vouchers',
        'unitPrice',
        'unitMeasure',
        'EV',
        'points'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->description)) {
            $json['description']       = $this->description;
        }
        $json['amount']                = $this->amount;
        $json['detailType']            = TransactionDetailType::checkValue($this->detailType);
        $json['discountAmount']        = $this->discountAmount;
        $json['offerInfos']            = $this->offerInfos;
        if (isset($this->offerLang)) {
            $json['offerLang']         = $this->offerLang;
        }
        $json['originalAmount']        = $this->originalAmount;
        if (isset($this->originalNetAmount)) {
            $json['originalNetAmount'] = $this->originalNetAmount;
        }
        $json['productData']           = $this->productData;
        $json['quantity']              = $this->quantity;
        if (isset($this->vatAmount)) {
            $json['vatAmount']         = $this->vatAmount;
        }
        if (isset($this->vatRate)) {
            $json['vatRate']           = $this->vatRate;
        }
        if (isset($this->voucherItems)) {
            $json['voucherItems']      = $this->voucherItems;
        }
        if (isset($this->vouchers)) {
            $json['vouchers']          = $this->vouchers;
        }
        if (isset($this->unitPrice)) {
            $json['unitPrice']         = $this->unitPrice;
        }
        if (isset($this->unitMeasure)) {
            $json['unitMeasure']       = UnitMeasure::checkValue($this->unitMeasure);
        }
        if (isset($this->ev)) {
            $json['EV']                = $this->ev;
        }
        if (isset($this->points)) {
            $json['points']            = $this->points;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
