<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class SaleItemProduct implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $productType;

    /**
     * @var string|null
     */
    private $productCode;

    /**
     * @var string|null
     */
    private $productDescription;

    /**
     * @var string|null
     */
    private $additionalProductDescription;

    /**
     * @param string $id
     * @param string $name
     * @param string $productType
     */
    public function __construct(string $id, string $name, string $productType)
    {
        $this->id = $id;
        $this->name = $name;
        $this->productType = $productType;
    }

    /**
     * Returns Id.
     * Unique Id of the product
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Unique Id of the product
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Name.
     * Name of the product
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name of the product
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Product Type.
     * Indicating the Type of the product (Fuel, CR, CC, PARTNER, OTHER, GREEN_ENERGY).
     */
    public function getProductType(): string
    {
        return $this->productType;
    }

    /**
     * Sets Product Type.
     * Indicating the Type of the product (Fuel, CR, CC, PARTNER, OTHER, GREEN_ENERGY).
     *
     * @required
     * @maps productType
     * @factory \LoyaltyApIsLib\Models\ProductType::checkValue
     */
    public function setProductType(string $productType): void
    {
        $this->productType = $productType;
    }

    /**
     * Returns Product Code.
     * Product code of gift item (euroShell Forward Code). To be populated with 3 digit Euroshell product
     * code.
     */
    public function getProductCode(): ?string
    {
        return $this->productCode;
    }

    /**
     * Sets Product Code.
     * Product code of gift item (euroShell Forward Code). To be populated with 3 digit Euroshell product
     * code.
     *
     * @maps productCode
     */
    public function setProductCode(?string $productCode): void
    {
        $this->productCode = $productCode;
    }

    /**
     * Returns Product Description.
     */
    public function getProductDescription(): ?string
    {
        return $this->productDescription;
    }

    /**
     * Sets Product Description.
     *
     * @maps productDescription
     */
    public function setProductDescription(?string $productDescription): void
    {
        $this->productDescription = $productDescription;
    }

    /**
     * Returns Additional Product Description.
     * Customer name of the product provided by the partner
     */
    public function getAdditionalProductDescription(): ?string
    {
        return $this->additionalProductDescription;
    }

    /**
     * Sets Additional Product Description.
     * Customer name of the product provided by the partner
     *
     * @maps additionalProductDescription
     */
    public function setAdditionalProductDescription(?string $additionalProductDescription): void
    {
        $this->additionalProductDescription = $additionalProductDescription;
    }

    /**
     * Converts the SaleItemProduct object to a human-readable string representation.
     *
     * @return string The string representation of the SaleItemProduct object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SaleItemProduct',
            [
                'id' => $this->id,
                'name' => $this->name,
                'productType' => $this->productType,
                'productCode' => $this->productCode,
                'productDescription' => $this->productDescription,
                'additionalProductDescription' => $this->additionalProductDescription,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'id',
        'name',
        'productType',
        'productCode',
        'productDescription',
        'additionalProductDescription'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']                               = $this->id;
        $json['name']                             = $this->name;
        $json['productType']                      = ProductType::checkValue($this->productType);
        if (isset($this->productCode)) {
            $json['productCode']                  = $this->productCode;
        }
        if (isset($this->productDescription)) {
            $json['productDescription']           = $this->productDescription;
        }
        if (isset($this->additionalProductDescription)) {
            $json['additionalProductDescription'] = $this->additionalProductDescription;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
