<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class SiteData implements \JsonSerializable
{
    /**
     * @var string
     */
    private $countryCode;

    /**
     * @var string
     */
    private $siteId;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string|null
     */
    private $postcode;

    /**
     * @var string|null
     */
    private $city;

    /**
     * @var string|null
     */
    private $address;

    /**
     * @param string $countryCode
     * @param string $siteId
     * @param string $name
     */
    public function __construct(string $countryCode, string $siteId, string $name)
    {
        $this->countryCode = $countryCode;
        $this->siteId = $siteId;
        $this->name = $name;
    }

    /**
     * Returns Country Code.
     * Two character ISO 3166-1 alpha-2 country code
     */
    public function getCountryCode(): string
    {
        return $this->countryCode;
    }

    /**
     * Sets Country Code.
     * Two character ISO 3166-1 alpha-2 country code
     *
     * @required
     * @maps countryCode
     */
    public function setCountryCode(string $countryCode): void
    {
        $this->countryCode = $countryCode;
    }

    /**
     * Returns Site Id.
     * Unique Id of the site
     */
    public function getSiteId(): string
    {
        return $this->siteId;
    }

    /**
     * Sets Site Id.
     * Unique Id of the site
     *
     * @required
     * @maps siteId
     */
    public function setSiteId(string $siteId): void
    {
        $this->siteId = $siteId;
    }

    /**
     * Returns Name.
     * Name of the site
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name of the site
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Postcode.
     * Postcode of the site
     */
    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    /**
     * Sets Postcode.
     * Postcode of the site
     *
     * @maps postcode
     */
    public function setPostcode(?string $postcode): void
    {
        $this->postcode = $postcode;
    }

    /**
     * Returns City.
     * City of the site
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * Sets City.
     * City of the site
     *
     * @maps city
     */
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns Address.
     * Address of the site
     */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * Sets Address.
     * Address of the site
     *
     * @maps address
     */
    public function setAddress(?string $address): void
    {
        $this->address = $address;
    }

    /**
     * Converts the SiteData object to a human-readable string representation.
     *
     * @return string The string representation of the SiteData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SiteData',
            [
                'countryCode' => $this->countryCode,
                'siteId' => $this->siteId,
                'name' => $this->name,
                'postcode' => $this->postcode,
                'city' => $this->city,
                'address' => $this->address,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['countryCode', 'siteId', 'name', 'postcode', 'city', 'address'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['countryCode']  = $this->countryCode;
        $json['siteId']       = $this->siteId;
        $json['name']         = $this->name;
        if (isset($this->postcode)) {
            $json['postcode'] = $this->postcode;
        }
        if (isset($this->city)) {
            $json['city']     = $this->city;
        }
        if (isset($this->address)) {
            $json['address']  = $this->address;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
