<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Indicates the Type of the transaction detail row (award, redemption, transfer, voucher, refund or
 * central award).
 */
class TransactionDetailType
{
    public const AWARD = 'AWARD';

    public const REDEMPTION = 'REDEMPTION';

    public const TRANSFER = 'TRANSFER';

    public const REFUND = 'REFUND';

    public const CENTRAL_AWARD = 'CENTRAL_AWARD';

    public const VOUCHER = 'VOUCHER';

    private const _ALL_VALUES =
        [self::AWARD, self::REDEMPTION, self::TRANSFER, self::REFUND, self::CENTRAL_AWARD, self::VOUCHER];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for TransactionDetailType.");
    }
}
