<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class TransactionVoucher implements \JsonSerializable
{
    /**
     * @var string
     */
    private $detailType;

    /**
     * @var string
     */
    private $code;

    /**
     * @var string
     */
    private $name;

    /**
     * @var float
     */
    private $amount;

    /**
     * @var float
     */
    private $quantity;

    /**
     * @param string $detailType
     * @param string $code
     * @param string $name
     * @param float $amount
     * @param float $quantity
     */
    public function __construct(string $detailType, string $code, string $name, float $amount, float $quantity)
    {
        $this->detailType = $detailType;
        $this->code = $code;
        $this->name = $name;
        $this->amount = $amount;
        $this->quantity = $quantity;
    }

    /**
     * Returns Detail Type.
     * Indicates the Type of the transaction detail row (award, redemption, transfer, voucher, refund or
     * central award).
     */
    public function getDetailType(): string
    {
        return $this->detailType;
    }

    /**
     * Sets Detail Type.
     * Indicates the Type of the transaction detail row (award, redemption, transfer, voucher, refund or
     * central award).
     *
     * @required
     * @maps detailType
     * @factory \LoyaltyApIsLib\Models\TransactionDetailType::checkValue
     */
    public function setDetailType(string $detailType): void
    {
        $this->detailType = $detailType;
    }

    /**
     * Returns Code.
     * Unique code of the voucher
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     * Unique code of the voucher
     *
     * @required
     * @maps code
     */
    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Name.
     * Name of the voucher
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name of the voucher
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Amount.
     * Sum amount of the voucher
     */
    public function getAmount(): float
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Sum amount of the voucher
     *
     * @required
     * @maps amount
     */
    public function setAmount(float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Quantity.
     * Quantity of vouchers
     */
    public function getQuantity(): float
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     * Quantity of vouchers
     *
     * @required
     * @maps quantity
     */
    public function setQuantity(float $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Converts the TransactionVoucher object to a human-readable string representation.
     *
     * @return string The string representation of the TransactionVoucher object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TransactionVoucher',
            [
                'detailType' => $this->detailType,
                'code' => $this->code,
                'name' => $this->name,
                'amount' => $this->amount,
                'quantity' => $this->quantity,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['detailType', 'code', 'name', 'amount', 'quantity'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['detailType'] = TransactionDetailType::checkValue($this->detailType);
        $json['code']       = $this->code;
        $json['name']       = $this->name;
        $json['amount']     = $this->amount;
        $json['quantity']   = $this->quantity;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
