<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class TransactionBalanceAmount implements \JsonSerializable
{
    /**
     * @var float
     */
    private $amount;

    /**
     * @var string
     */
    private $state;

    /**
     * @param float $amount
     * @param string $state
     */
    public function __construct(float $amount, string $state)
    {
        $this->amount = $amount;
        $this->state = $state;
    }

    /**
     * Returns Amount.
     * Current value of specified balance
     */
    public function getAmount(): float
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * Current value of specified balance
     *
     * @required
     * @maps amount
     */
    public function setAmount(float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns State.
     * State of the amount
     */
    public function getState(): string
    {
        return $this->state;
    }

    /**
     * Sets State.
     * State of the amount
     *
     * @required
     * @maps state
     * @factory \LoyaltyApIsLib\Models\TransactionBalanceState::checkValue
     */
    public function setState(string $state): void
    {
        $this->state = $state;
    }

    /**
     * Converts the TransactionBalanceAmount object to a human-readable string representation.
     *
     * @return string The string representation of the TransactionBalanceAmount object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TransactionBalanceAmount',
            [
                'amount' => $this->amount,
                'state' => $this->state,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['amount', 'state'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['amount'] = $this->amount;
        $json['state']  = TransactionBalanceState::checkValue($this->state);
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
