<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use LoyaltyApIsLib\Utils\DateTimeHelper;
use stdClass;

class Transaction implements \JsonSerializable
{
    /**
     * @var int
     */
    private $transactionDateTime;

    /**
     * @var \DateTime|null
     */
    private $transactionDateTimeStamp;

    /**
     * @var SiteData
     */
    private $siteData;

    /**
     * @var LoyaltyCardInfo
     */
    private $loyalty;

    /**
     * @var string|null
     */
    private $transactionId;

    /**
     * @var string|null
     */
    private $partnerCode;

    /**
     * @var string|null
     */
    private $partnerName;

    /**
     * @var string|null
     */
    private $partnerLogo;

    /**
     * @var string|null
     */
    private $referenceId;

    /**
     * @var float
     */
    private $totalAmount;

    /**
     * @var float
     */
    private $totalDiscountAmount;

    /**
     * @var float
     */
    private $totalDiscountedFullAmount;

    /**
     * @var float|null
     */
    private $totalVatAmount;

    /**
     * @var TransactionBalance[]|null
     */
    private $balances;

    /**
     * @var string|null
     */
    private $currencyCode;

    /**
     * @var SaleItem[]
     */
    private $saleItems;

    /**
     * @var RedeemedItem[]
     */
    private $redeemedItems;

    /**
     * @var TransactionVoucher[]
     */
    private $transactionVouchers;

    /**
     * @var string|null
     */
    private $receiptNumber;

    /**
     * @var PointsToCash|null
     */
    private $pointsToCash;

    /**
     * @var int|null
     */
    private $companyId;

    /**
     * @var bool|null
     */
    private $isPartnerRedemption;

    /**
     * @var CurrencyData|null
     */
    private $currencyData;

    /**
     * @param int $transactionDateTime
     * @param SiteData $siteData
     * @param LoyaltyCardInfo $loyalty
     * @param float $totalAmount
     * @param float $totalDiscountAmount
     * @param float $totalDiscountedFullAmount
     * @param SaleItem[] $saleItems
     * @param RedeemedItem[] $redeemedItems
     * @param TransactionVoucher[] $transactionVouchers
     */
    public function __construct(
        int $transactionDateTime,
        SiteData $siteData,
        LoyaltyCardInfo $loyalty,
        float $totalAmount,
        float $totalDiscountAmount,
        float $totalDiscountedFullAmount,
        array $saleItems,
        array $redeemedItems,
        array $transactionVouchers
    ) {
        $this->transactionDateTime = $transactionDateTime;
        $this->siteData = $siteData;
        $this->loyalty = $loyalty;
        $this->totalAmount = $totalAmount;
        $this->totalDiscountAmount = $totalDiscountAmount;
        $this->totalDiscountedFullAmount = $totalDiscountedFullAmount;
        $this->saleItems = $saleItems;
        $this->redeemedItems = $redeemedItems;
        $this->transactionVouchers = $transactionVouchers;
    }

    /**
     * Returns Transaction Date Time.
     * Transaction date as Unix epoch (UTC), as requested by MobGen.
     */
    public function getTransactionDateTime(): int
    {
        return $this->transactionDateTime;
    }

    /**
     * Sets Transaction Date Time.
     * Transaction date as Unix epoch (UTC), as requested by MobGen.
     *
     * @required
     * @maps transactionDateTime
     */
    public function setTransactionDateTime(int $transactionDateTime): void
    {
        $this->transactionDateTime = $transactionDateTime;
    }

    /**
     * Returns Transaction Date Time Stamp.
     * Transaction date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ”
     */
    public function getTransactionDateTimeStamp(): ?\DateTime
    {
        return $this->transactionDateTimeStamp;
    }

    /**
     * Sets Transaction Date Time Stamp.
     * Transaction date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ”
     *
     * @maps transactionDateTimeStamp
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTransactionDateTimeStamp(?\DateTime $transactionDateTimeStamp): void
    {
        $this->transactionDateTimeStamp = $transactionDateTimeStamp;
    }

    /**
     * Returns Site Data.
     */
    public function getSiteData(): SiteData
    {
        return $this->siteData;
    }

    /**
     * Sets Site Data.
     *
     * @required
     * @maps siteData
     */
    public function setSiteData(SiteData $siteData): void
    {
        $this->siteData = $siteData;
    }

    /**
     * Returns Loyalty.
     */
    public function getLoyalty(): LoyaltyCardInfo
    {
        return $this->loyalty;
    }

    /**
     * Sets Loyalty.
     *
     * @required
     * @maps loyalty
     */
    public function setLoyalty(LoyaltyCardInfo $loyalty): void
    {
        $this->loyalty = $loyalty;
    }

    /**
     * Returns Transaction Id.
     * Unique Id of the transaction row.
     */
    public function getTransactionId(): ?string
    {
        return $this->transactionId;
    }

    /**
     * Sets Transaction Id.
     * Unique Id of the transaction row.
     *
     * @maps transactionId
     */
    public function setTransactionId(?string $transactionId): void
    {
        $this->transactionId = $transactionId;
    }

    /**
     * Returns Partner Code.
     * Unique code identifying the partner
     */
    public function getPartnerCode(): ?string
    {
        return $this->partnerCode;
    }

    /**
     * Sets Partner Code.
     * Unique code identifying the partner
     *
     * @maps partnerCode
     */
    public function setPartnerCode(?string $partnerCode): void
    {
        $this->partnerCode = $partnerCode;
    }

    /**
     * Returns Partner Name.
     * Name of the partner
     */
    public function getPartnerName(): ?string
    {
        return $this->partnerName;
    }

    /**
     * Sets Partner Name.
     * Name of the partner
     *
     * @maps partnerName
     */
    public function setPartnerName(?string $partnerName): void
    {
        $this->partnerName = $partnerName;
    }

    /**
     * Returns Partner Logo.
     */
    public function getPartnerLogo(): ?string
    {
        return $this->partnerLogo;
    }

    /**
     * Sets Partner Logo.
     *
     * @maps partnerLogo
     */
    public function setPartnerLogo(?string $partnerLogo): void
    {
        $this->partnerLogo = $partnerLogo;
    }

    /**
     * Returns Reference Id.
     * Reference ID for each transaction. It is unique for each partner and transaction.
     */
    public function getReferenceId(): ?string
    {
        return $this->referenceId;
    }

    /**
     * Sets Reference Id.
     * Reference ID for each transaction. It is unique for each partner and transaction.
     *
     * @maps referenceId
     */
    public function setReferenceId(?string $referenceId): void
    {
        $this->referenceId = $referenceId;
    }

    /**
     * Returns Total Amount.
     * Total amount of the transaction.
     */
    public function getTotalAmount(): float
    {
        return $this->totalAmount;
    }

    /**
     * Sets Total Amount.
     * Total amount of the transaction.
     *
     * @required
     * @maps totalAmount
     */
    public function setTotalAmount(float $totalAmount): void
    {
        $this->totalAmount = $totalAmount;
    }

    /**
     * Returns Total Discount Amount.
     * Total discount amount of the transaction.
     */
    public function getTotalDiscountAmount(): float
    {
        return $this->totalDiscountAmount;
    }

    /**
     * Sets Total Discount Amount.
     * Total discount amount of the transaction.
     *
     * @required
     * @maps totalDiscountAmount
     */
    public function setTotalDiscountAmount(float $totalDiscountAmount): void
    {
        $this->totalDiscountAmount = $totalDiscountAmount;
    }

    /**
     * Returns Total Discounted Full Amount.
     * totalAmount - totalDiscountedFullAmount
     */
    public function getTotalDiscountedFullAmount(): float
    {
        return $this->totalDiscountedFullAmount;
    }

    /**
     * Sets Total Discounted Full Amount.
     * totalAmount - totalDiscountedFullAmount
     *
     * @required
     * @maps totalDiscountedFullAmount
     */
    public function setTotalDiscountedFullAmount(float $totalDiscountedFullAmount): void
    {
        $this->totalDiscountedFullAmount = $totalDiscountedFullAmount;
    }

    /**
     * Returns Total Vat Amount.
     * Total amount of VAT
     */
    public function getTotalVatAmount(): ?float
    {
        return $this->totalVatAmount;
    }

    /**
     * Sets Total Vat Amount.
     * Total amount of VAT
     *
     * @maps totalVatAmount
     */
    public function setTotalVatAmount(?float $totalVatAmount): void
    {
        $this->totalVatAmount = $totalVatAmount;
    }

    /**
     * Returns Balances.
     *
     * @return TransactionBalance[]|null
     */
    public function getBalances(): ?array
    {
        return $this->balances;
    }

    /**
     * Sets Balances.
     *
     * @maps balances
     *
     * @param TransactionBalance[]|null $balances
     */
    public function setBalances(?array $balances): void
    {
        $this->balances = $balances;
    }

    /**
     * Returns Currency Code.
     * Currency using ISO4217 alpha-3 currency code
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     * Currency using ISO4217 alpha-3 currency code
     *
     * @maps currencyCode
     */
    public function setCurrencyCode(?string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Sale Items.
     *
     * @return SaleItem[]
     */
    public function getSaleItems(): array
    {
        return $this->saleItems;
    }

    /**
     * Sets Sale Items.
     *
     * @required
     * @maps saleItems
     *
     * @param SaleItem[] $saleItems
     */
    public function setSaleItems(array $saleItems): void
    {
        $this->saleItems = $saleItems;
    }

    /**
     * Returns Redeemed Items.
     *
     * @return RedeemedItem[]
     */
    public function getRedeemedItems(): array
    {
        return $this->redeemedItems;
    }

    /**
     * Sets Redeemed Items.
     *
     * @required
     * @maps redeemedItems
     *
     * @param RedeemedItem[] $redeemedItems
     */
    public function setRedeemedItems(array $redeemedItems): void
    {
        $this->redeemedItems = $redeemedItems;
    }

    /**
     * Returns Transaction Vouchers.
     *
     * @return TransactionVoucher[]
     */
    public function getTransactionVouchers(): array
    {
        return $this->transactionVouchers;
    }

    /**
     * Sets Transaction Vouchers.
     *
     * @required
     * @maps transactionVouchers
     *
     * @param TransactionVoucher[] $transactionVouchers
     */
    public function setTransactionVouchers(array $transactionVouchers): void
    {
        $this->transactionVouchers = $transactionVouchers;
    }

    /**
     * Returns Receipt Number.
     * Unique number of transaction's receipt
     */
    public function getReceiptNumber(): ?string
    {
        return $this->receiptNumber;
    }

    /**
     * Sets Receipt Number.
     * Unique number of transaction's receipt
     *
     * @maps receiptNumber
     */
    public function setReceiptNumber(?string $receiptNumber): void
    {
        $this->receiptNumber = $receiptNumber;
    }

    /**
     * Returns Points to Cash.
     */
    public function getPointsToCash(): ?PointsToCash
    {
        return $this->pointsToCash;
    }

    /**
     * Sets Points to Cash.
     *
     * @maps pointsToCash
     */
    public function setPointsToCash(?PointsToCash $pointsToCash): void
    {
        $this->pointsToCash = $pointsToCash;
    }

    /**
     * Returns Company Id.
     * Partner identifier
     */
    public function getCompanyId(): ?int
    {
        return $this->companyId;
    }

    /**
     * Sets Company Id.
     * Partner identifier
     *
     * @maps companyId
     */
    public function setCompanyId(?int $companyId): void
    {
        $this->companyId = $companyId;
    }

    /**
     * Returns Is Partner Redemption.
     * Describes whether the transaction is partner redemption.
     */
    public function getIsPartnerRedemption(): ?bool
    {
        return $this->isPartnerRedemption;
    }

    /**
     * Sets Is Partner Redemption.
     * Describes whether the transaction is partner redemption.
     *
     * @maps isPartnerRedemption
     */
    public function setIsPartnerRedemption(?bool $isPartnerRedemption): void
    {
        $this->isPartnerRedemption = $isPartnerRedemption;
    }

    /**
     * Returns Currency Data.
     * currencyData is only filled, where there is possible non-same currency cross-border transaction
     */
    public function getCurrencyData(): ?CurrencyData
    {
        return $this->currencyData;
    }

    /**
     * Sets Currency Data.
     * currencyData is only filled, where there is possible non-same currency cross-border transaction
     *
     * @maps currencyData
     */
    public function setCurrencyData(?CurrencyData $currencyData): void
    {
        $this->currencyData = $currencyData;
    }

    /**
     * Converts the Transaction object to a human-readable string representation.
     *
     * @return string The string representation of the Transaction object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Transaction',
            [
                'transactionDateTime' => $this->transactionDateTime,
                'transactionDateTimeStamp' => $this->transactionDateTimeStamp,
                'siteData' => $this->siteData,
                'loyalty' => $this->loyalty,
                'transactionId' => $this->transactionId,
                'partnerCode' => $this->partnerCode,
                'partnerName' => $this->partnerName,
                'partnerLogo' => $this->partnerLogo,
                'referenceId' => $this->referenceId,
                'totalAmount' => $this->totalAmount,
                'totalDiscountAmount' => $this->totalDiscountAmount,
                'totalDiscountedFullAmount' => $this->totalDiscountedFullAmount,
                'totalVatAmount' => $this->totalVatAmount,
                'balances' => $this->balances,
                'currencyCode' => $this->currencyCode,
                'saleItems' => $this->saleItems,
                'redeemedItems' => $this->redeemedItems,
                'transactionVouchers' => $this->transactionVouchers,
                'receiptNumber' => $this->receiptNumber,
                'pointsToCash' => $this->pointsToCash,
                'companyId' => $this->companyId,
                'isPartnerRedemption' => $this->isPartnerRedemption,
                'currencyData' => $this->currencyData,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'transactionDateTime',
        'transactionDateTimeStamp',
        'siteData',
        'loyalty',
        'transactionId',
        'partnerCode',
        'partnerName',
        'partnerLogo',
        'referenceId',
        'totalAmount',
        'totalDiscountAmount',
        'totalDiscountedFullAmount',
        'totalVatAmount',
        'balances',
        'currencyCode',
        'saleItems',
        'redeemedItems',
        'transactionVouchers',
        'receiptNumber',
        'pointsToCash',
        'companyId',
        'isPartnerRedemption',
        'currencyData'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['transactionDateTime']          = $this->transactionDateTime;
        if (isset($this->transactionDateTimeStamp)) {
            $json['transactionDateTimeStamp'] = DateTimeHelper::toRfc3339DateTime($this->transactionDateTimeStamp);
        }
        $json['siteData']                     = $this->siteData;
        $json['loyalty']                      = $this->loyalty;
        if (isset($this->transactionId)) {
            $json['transactionId']            = $this->transactionId;
        }
        if (isset($this->partnerCode)) {
            $json['partnerCode']              = $this->partnerCode;
        }
        if (isset($this->partnerName)) {
            $json['partnerName']              = $this->partnerName;
        }
        if (isset($this->partnerLogo)) {
            $json['partnerLogo']              = $this->partnerLogo;
        }
        if (isset($this->referenceId)) {
            $json['referenceId']              = $this->referenceId;
        }
        $json['totalAmount']                  = $this->totalAmount;
        $json['totalDiscountAmount']          = $this->totalDiscountAmount;
        $json['totalDiscountedFullAmount']    = $this->totalDiscountedFullAmount;
        if (isset($this->totalVatAmount)) {
            $json['totalVatAmount']           = $this->totalVatAmount;
        }
        if (isset($this->balances)) {
            $json['balances']                 = $this->balances;
        }
        if (isset($this->currencyCode)) {
            $json['currencyCode']             = $this->currencyCode;
        }
        $json['saleItems']                    = $this->saleItems;
        $json['redeemedItems']                = $this->redeemedItems;
        $json['transactionVouchers']          = $this->transactionVouchers;
        if (isset($this->receiptNumber)) {
            $json['receiptNumber']            = $this->receiptNumber;
        }
        if (isset($this->pointsToCash)) {
            $json['pointsToCash']             = $this->pointsToCash;
        }
        if (isset($this->companyId)) {
            $json['companyId']                = $this->companyId;
        }
        if (isset($this->isPartnerRedemption)) {
            $json['isPartnerRedemption']      = $this->isPartnerRedemption;
        }
        if (isset($this->currencyData)) {
            $json['currencyData']             = $this->currencyData;
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
