<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class TransactionsResponse implements \JsonSerializable
{
    /**
     * @var int
     */
    private $totalResults;

    /**
     * @var string
     */
    private $nextPage;

    /**
     * @var string
     */
    private $previousPage;

    /**
     * @var float
     */
    private $totalSaved;

    /**
     * @var Transaction[]
     */
    private $transactions;

    /**
     * @param int $totalResults
     * @param string $nextPage
     * @param string $previousPage
     * @param float $totalSaved
     * @param Transaction[] $transactions
     */
    public function __construct(
        int $totalResults,
        string $nextPage,
        string $previousPage,
        float $totalSaved,
        array $transactions
    ) {
        $this->totalResults = $totalResults;
        $this->nextPage = $nextPage;
        $this->previousPage = $previousPage;
        $this->totalSaved = $totalSaved;
        $this->transactions = $transactions;
    }

    /**
     * Returns Total Results.
     * Total no of resource which will be sent back across all pages
     */
    public function getTotalResults(): int
    {
        return $this->totalResults;
    }

    /**
     * Sets Total Results.
     * Total no of resource which will be sent back across all pages
     *
     * @required
     * @maps totalResults
     */
    public function setTotalResults(int $totalResults): void
    {
        $this->totalResults = $totalResults;
    }

    /**
     * Returns Next Page.
     * API URI which must be used to retrieve the next page of resources
     */
    public function getNextPage(): string
    {
        return $this->nextPage;
    }

    /**
     * Sets Next Page.
     * API URI which must be used to retrieve the next page of resources
     *
     * @required
     * @maps nextPage
     */
    public function setNextPage(string $nextPage): void
    {
        $this->nextPage = $nextPage;
    }

    /**
     * Returns Previous Page.
     * API URI which must be used to retrieve the previous page of resources
     */
    public function getPreviousPage(): string
    {
        return $this->previousPage;
    }

    /**
     * Sets Previous Page.
     * API URI which must be used to retrieve the previous page of resources
     *
     * @required
     * @maps previousPage
     */
    public function setPreviousPage(string $previousPage): void
    {
        $this->previousPage = $previousPage;
    }

    /**
     * Returns Total Saved.
     * Total amount saved so far
     */
    public function getTotalSaved(): float
    {
        return $this->totalSaved;
    }

    /**
     * Sets Total Saved.
     * Total amount saved so far
     *
     * @required
     * @maps totalSaved
     */
    public function setTotalSaved(float $totalSaved): void
    {
        $this->totalSaved = $totalSaved;
    }

    /**
     * Returns Transactions.
     * Transactions list
     *
     * @return Transaction[]
     */
    public function getTransactions(): array
    {
        return $this->transactions;
    }

    /**
     * Sets Transactions.
     * Transactions list
     *
     * @required
     * @maps transactions
     *
     * @param Transaction[] $transactions
     */
    public function setTransactions(array $transactions): void
    {
        $this->transactions = $transactions;
    }

    /**
     * Converts the TransactionsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the TransactionsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TransactionsResponse',
            [
                'totalResults' => $this->totalResults,
                'nextPage' => $this->nextPage,
                'previousPage' => $this->previousPage,
                'totalSaved' => $this->totalSaved,
                'transactions' => $this->transactions,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['totalResults', 'nextPage', 'previousPage', 'totalSaved', 'transactions'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['totalResults'] = $this->totalResults;
        $json['nextPage']     = $this->nextPage;
        $json['previousPage'] = $this->previousPage;
        $json['totalSaved']   = $this->totalSaved;
        $json['transactions'] = $this->transactions;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
