<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

class TransactionBalance implements \JsonSerializable
{
    /**
     * @var string
     */
    private $currencyType;

    /**
     * @var TransactionBalanceAmount[]
     */
    private $amounts;

    /**
     * @param string $currencyType
     * @param TransactionBalanceAmount[] $amounts
     */
    public function __construct(string $currencyType, array $amounts)
    {
        $this->currencyType = $currencyType;
        $this->amounts = $amounts;
    }

    /**
     * Returns Currency Type.
     * Type of balance
     */
    public function getCurrencyType(): string
    {
        return $this->currencyType;
    }

    /**
     * Sets Currency Type.
     * Type of balance
     *
     * @required
     * @maps currencyType
     * @factory \LoyaltyApIsLib\Models\TransactionCurrencyType::checkValue
     */
    public function setCurrencyType(string $currencyType): void
    {
        $this->currencyType = $currencyType;
    }

    /**
     * Returns Amounts.
     *
     * @return TransactionBalanceAmount[]
     */
    public function getAmounts(): array
    {
        return $this->amounts;
    }

    /**
     * Sets Amounts.
     *
     * @required
     * @maps amounts
     *
     * @param TransactionBalanceAmount[] $amounts
     */
    public function setAmounts(array $amounts): void
    {
        $this->amounts = $amounts;
    }

    /**
     * Converts the TransactionBalance object to a human-readable string representation.
     *
     * @return string The string representation of the TransactionBalance object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TransactionBalance',
            [
                'currencyType' => $this->currencyType,
                'amounts' => $this->amounts,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['currencyType', 'amounts'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['currencyType'] = TransactionCurrencyType::checkValue($this->currencyType);
        $json['amounts']      = $this->amounts;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
