<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use stdClass;

/**
 * The application is not authorised to use the requested grant type.
 */
class UnauthorizedError implements \JsonSerializable
{
    /**
     * @var Fault|null
     */
    private $fault;

    /**
     * Returns Fault.
     */
    public function getFault(): ?Fault
    {
        return $this->fault;
    }

    /**
     * Sets Fault.
     *
     * @maps fault
     */
    public function setFault(?Fault $fault): void
    {
        $this->fault = $fault;
    }

    /**
     * Converts the UnauthorizedError object to a human-readable string representation.
     *
     * @return string The string representation of the UnauthorizedError object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('UnauthorizedError', ['fault' => $this->fault]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->fault)) {
            $json['fault'] = $this->fault;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
