<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib\Models;

use LoyaltyApIsLib\ApiHelper;
use LoyaltyApIsLib\Utils\DateTimeHelper;
use stdClass;

class VoucherItem implements \JsonSerializable
{
    /**
     * @var string
     */
    private $code;

    /**
     * @var int
     */
    private $expiryDate;

    /**
     * @var \DateTime
     */
    private $expiryDateTimestamp;

    /**
     * @param string $code
     * @param int $expiryDate
     * @param \DateTime $expiryDateTimestamp
     */
    public function __construct(string $code, int $expiryDate, \DateTime $expiryDateTimestamp)
    {
        $this->code = $code;
        $this->expiryDate = $expiryDate;
        $this->expiryDateTimestamp = $expiryDateTimestamp;
    }

    /**
     * Returns Code.
     * Voucher code
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     * Voucher code
     *
     * @required
     * @maps code
     */
    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Expiry Date.
     * Expiry date as Unix epoch (UTC), as requested by MobGen.
     */
    public function getExpiryDate(): int
    {
        return $this->expiryDate;
    }

    /**
     * Sets Expiry Date.
     * Expiry date as Unix epoch (UTC), as requested by MobGen.
     *
     * @required
     * @maps expiryDate
     */
    public function setExpiryDate(int $expiryDate): void
    {
        $this->expiryDate = $expiryDate;
    }

    /**
     * Returns Expiry Date Timestamp.
     * Expiry date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ”
     */
    public function getExpiryDateTimestamp(): \DateTime
    {
        return $this->expiryDateTimestamp;
    }

    /**
     * Sets Expiry Date Timestamp.
     * Expiry date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ”
     *
     * @required
     * @maps expiryDateTimestamp
     * @factory \LoyaltyApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setExpiryDateTimestamp(\DateTime $expiryDateTimestamp): void
    {
        $this->expiryDateTimestamp = $expiryDateTimestamp;
    }

    /**
     * Converts the VoucherItem object to a human-readable string representation.
     *
     * @return string The string representation of the VoucherItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VoucherItem',
            [
                'code' => $this->code,
                'expiryDate' => $this->expiryDate,
                'expiryDateTimestamp' => $this->expiryDateTimestamp,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['code', 'expiryDate', 'expiryDateTimestamp'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['code']                = $this->code;
        $json['expiryDate']          = $this->expiryDate;
        $json['expiryDateTimestamp'] = DateTimeHelper::toRfc3339DateTime($this->expiryDateTimestamp);
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
