<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib;

use CoreInterfaces\Http\HttpConfigurations;
use LoyaltyApIsLib\Authentication\ClientAuthorizationTokenCredentials;
use LoyaltyApIsLib\Authentication\ClientAuthorizationTokenCredentialsBuilder;
use LoyaltyApIsLib\Authentication\CustomerHeaderCredentials;
use LoyaltyApIsLib\Authentication\CustomerHeaderCredentialsBuilder;
use LoyaltyApIsLib\Authentication\PrivateBasicTokenCredentials;
use LoyaltyApIsLib\Authentication\PrivateBasicTokenCredentialsBuilder;
use LoyaltyApIsLib\Authentication\PublicBasicTokenCredentials;
use LoyaltyApIsLib\Authentication\PublicBasicTokenCredentialsBuilder;
use LoyaltyApIsLib\Authentication\PublicBearerTokenCredentials;
use LoyaltyApIsLib\Authentication\PublicBearerTokenCredentialsBuilder;
use LoyaltyApIsLib\Logging\LoggingConfigurationBuilder;
use LoyaltyApIsLib\Proxy\ProxyConfigurationBuilder;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface extends HttpConfigurations
{
    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the credentials to use with PublicBearerToken
     */
    public function getPublicBearerTokenCredentials(): PublicBearerTokenCredentials;

    /**
     * Get the credentials builder instance to update credentials for PublicBearerToken
     */
    public function getPublicBearerTokenCredentialsBuilder(): ?PublicBearerTokenCredentialsBuilder;

    /**
     * Get the credentials to use with PublicBasicToken
     */
    public function getPublicBasicTokenCredentials(): PublicBasicTokenCredentials;

    /**
     * Get the credentials builder instance to update credentials for PublicBasicToken
     */
    public function getPublicBasicTokenCredentialsBuilder(): ?PublicBasicTokenCredentialsBuilder;

    /**
     * Get the credentials to use with PrivateBasicToken
     */
    public function getPrivateBasicTokenCredentials(): PrivateBasicTokenCredentials;

    /**
     * Get the credentials builder instance to update credentials for PrivateBasicToken
     */
    public function getPrivateBasicTokenCredentialsBuilder(): ?PrivateBasicTokenCredentialsBuilder;

    /**
     * Get the credentials to use with ClientAuthorizationToken
     */
    public function getClientAuthorizationTokenCredentials(): ClientAuthorizationTokenCredentials;

    /**
     * Get the credentials builder instance to update credentials for ClientAuthorizationToken
     */
    public function getClientAuthorizationTokenCredentialsBuilder(): ?ClientAuthorizationTokenCredentialsBuilder;

    /**
     * Get the credentials to use with CustomerHeader
     */
    public function getCustomerHeaderCredentials(): CustomerHeaderCredentials;

    /**
     * Get the credentials builder instance to update credentials for CustomerHeader
     */
    public function getCustomerHeaderCredentialsBuilder(): ?CustomerHeaderCredentialsBuilder;

    /**
     * Represents the logging configurations for API calls.
     */
    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder;

    /**
     * Represents the proxy configurations for API calls.
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder;

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::SHELL): string;
}
