<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib;

/**
 * Environments available for API
 */
class Environment
{
    public const SIT = 'SIT';

    public const PRODUCTION = 'Production';

    public const UAT = 'UAT';
}
