<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib;

use Core\ClientBuilder;
use Core\Utils\CoreHelper;
use LoyaltyApIsLib\Apis\AuthorizationApi;
use LoyaltyApIsLib\Apis\BalancesApi;
use LoyaltyApIsLib\Apis\OauthAuthorizationApi;
use LoyaltyApIsLib\Apis\OfferApi;
use LoyaltyApIsLib\Apis\ProfileManagementApi;
use LoyaltyApIsLib\Apis\RedemptionApi;
use LoyaltyApIsLib\Apis\TransactionApi;
use LoyaltyApIsLib\Authentication\ClientAuthorizationTokenCredentials;
use LoyaltyApIsLib\Authentication\ClientAuthorizationTokenCredentialsBuilder;
use LoyaltyApIsLib\Authentication\ClientAuthorizationTokenManager;
use LoyaltyApIsLib\Authentication\CustomerHeaderCredentials;
use LoyaltyApIsLib\Authentication\CustomerHeaderCredentialsBuilder;
use LoyaltyApIsLib\Authentication\CustomerHeaderManager;
use LoyaltyApIsLib\Authentication\PrivateBasicTokenCredentials;
use LoyaltyApIsLib\Authentication\PrivateBasicTokenCredentialsBuilder;
use LoyaltyApIsLib\Authentication\PrivateBasicTokenManager;
use LoyaltyApIsLib\Authentication\PublicBasicTokenCredentials;
use LoyaltyApIsLib\Authentication\PublicBasicTokenCredentialsBuilder;
use LoyaltyApIsLib\Authentication\PublicBasicTokenManager;
use LoyaltyApIsLib\Authentication\PublicBearerTokenCredentials;
use LoyaltyApIsLib\Authentication\PublicBearerTokenCredentialsBuilder;
use LoyaltyApIsLib\Authentication\PublicBearerTokenManager;
use LoyaltyApIsLib\Logging\LoggingConfigurationBuilder;
use LoyaltyApIsLib\Logging\RequestLoggingConfigurationBuilder;
use LoyaltyApIsLib\Logging\ResponseLoggingConfigurationBuilder;
use LoyaltyApIsLib\Proxy\ProxyConfigurationBuilder;
use LoyaltyApIsLib\Utils\CompatibilityConverter;
use Unirest\Configuration;
use Unirest\HttpClient;

class LoyaltyApIsClient implements ConfigurationInterface
{
    private $authorization;

    private $profileManagement;

    private $offer;

    private $balances;

    private $redemption;

    private $transaction;

    private $oauthAuthorization;

    private $publicBearerTokenManager;

    private $publicBasicTokenManager;

    private $privateBasicTokenManager;

    private $clientAuthorizationTokenManager;

    private $customerHeaderManager;

    private $loggingConfigurationBuilder;

    private $proxyConfiguration;

    private $config;

    private $client;

    /**
     * @see LoyaltyApIsClientBuilder::init()
     * @see LoyaltyApIsClientBuilder::build()
     *
     * @param array $config
     */
    public function __construct(array $config = [])
    {
        $this->config = array_merge(ConfigurationDefaults::_ALL, CoreHelper::clone($config));
        $this->publicBearerTokenManager = new PublicBearerTokenManager($this->config);
        $this->publicBasicTokenManager = new PublicBasicTokenManager($this->config);
        $this->privateBasicTokenManager = new PrivateBasicTokenManager($this->config);
        $this->clientAuthorizationTokenManager = new ClientAuthorizationTokenManager($this->config);
        $this->customerHeaderManager = new CustomerHeaderManager($this->config);
        $loggingConfiguration = null;
        if ($this->config['loggingConfiguration'] instanceof LoggingConfigurationBuilder) {
            $this->loggingConfigurationBuilder = $this->config['loggingConfiguration'];
            $loggingConfiguration = $this->loggingConfigurationBuilder->build();
        }
        $this->proxyConfiguration = $this->config['proxyConfiguration'] ?? ConfigurationDefaults::PROXY_CONFIGURATION;
        $this->client = ClientBuilder::init(
            new HttpClient(Configuration::init($this)->proxyConfiguration($this->proxyConfiguration))
        )
            ->converter(new CompatibilityConverter())
            ->jsonHelper(ApiHelper::getJsonHelper())
            ->apiCallback($this->config['httpCallback'] ?? null)
            ->userAgent('PHP-SDK/0.0.1 (OS: {os-info}, Engine: {engine}/{engine-version})')
            ->serverUrls(self::ENVIRONMENT_MAP[$this->getEnvironment()], Server::SHELL)
            ->authManagers([
                'PublicBearerToken' => $this->publicBearerTokenManager,
                'PublicBasicToken' => $this->publicBasicTokenManager,
                'PrivateBasicToken' => $this->privateBasicTokenManager,
                'client-authorization-token' => $this->clientAuthorizationTokenManager,
                'customerHeader' => $this->customerHeaderManager
            ])
            ->loggingConfiguration($loggingConfiguration)
            ->build();
        $this->clientAuthorizationTokenManager->setClient($this->client);
    }

    /**
     * Create a builder with the current client's configurations.
     *
     * @return LoyaltyApIsClientBuilder LoyaltyApIsClientBuilder instance
     */
    public function toBuilder(): LoyaltyApIsClientBuilder
    {
        $builder = LoyaltyApIsClientBuilder::init()
            ->timeout($this->getTimeout())
            ->enableRetries($this->shouldEnableRetries())
            ->numberOfRetries($this->getNumberOfRetries())
            ->retryInterval($this->getRetryInterval())
            ->backOffFactor($this->getBackOffFactor())
            ->maximumRetryWaitTime($this->getMaximumRetryWaitTime())
            ->retryOnTimeout($this->shouldRetryOnTimeout())
            ->httpStatusCodesToRetry($this->getHttpStatusCodesToRetry())
            ->httpMethodsToRetry($this->getHttpMethodsToRetry())
            ->environment($this->getEnvironment())
            ->httpCallback($this->config['httpCallback'] ?? null)
            ->proxyConfiguration($this->getProxyConfigurationBuilder());

        $publicBearerToken = $this->getPublicBearerTokenCredentialsBuilder();
        if ($publicBearerToken != null) {
            $builder->publicBearerTokenCredentials($publicBearerToken);
        }

        $publicBasicToken = $this->getPublicBasicTokenCredentialsBuilder();
        if ($publicBasicToken != null) {
            $builder->publicBasicTokenCredentials($publicBasicToken);
        }

        $privateBasicToken = $this->getPrivateBasicTokenCredentialsBuilder();
        if ($privateBasicToken != null) {
            $builder->privateBasicTokenCredentials($privateBasicToken);
        }

        $clientAuthorizationToken = $this->getClientAuthorizationTokenCredentialsBuilder();
        if ($clientAuthorizationToken != null) {
            $builder->clientAuthorizationTokenCredentials($clientAuthorizationToken);
        }

        $customerHeader = $this->getCustomerHeaderCredentialsBuilder();
        if ($customerHeader != null) {
            $builder->customerHeaderCredentials($customerHeader);
        }
        $loggingConfigurationBuilder = $this->getLoggingConfigurationBuilder();
        if ($loggingConfigurationBuilder != null) {
            $builder->loggingConfiguration($loggingConfigurationBuilder);
        }
        return $builder;
    }

    public function getTimeout(): int
    {
        return $this->config['timeout'] ?? ConfigurationDefaults::TIMEOUT;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->config['enableRetries'] ?? ConfigurationDefaults::ENABLE_RETRIES;
    }

    public function getNumberOfRetries(): int
    {
        return $this->config['numberOfRetries'] ?? ConfigurationDefaults::NUMBER_OF_RETRIES;
    }

    public function getRetryInterval(): float
    {
        return $this->config['retryInterval'] ?? ConfigurationDefaults::RETRY_INTERVAL;
    }

    public function getBackOffFactor(): float
    {
        return $this->config['backOffFactor'] ?? ConfigurationDefaults::BACK_OFF_FACTOR;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->config['maximumRetryWaitTime'] ?? ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->config['retryOnTimeout'] ?? ConfigurationDefaults::RETRY_ON_TIMEOUT;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->config['httpStatusCodesToRetry'] ?? ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->config['httpMethodsToRetry'] ?? ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    }

    public function getEnvironment(): string
    {
        return $this->config['environment'] ?? ConfigurationDefaults::ENVIRONMENT;
    }

    public function getPublicBearerTokenCredentials(): PublicBearerTokenCredentials
    {
        return $this->publicBearerTokenManager;
    }

    public function getPublicBearerTokenCredentialsBuilder(): ?PublicBearerTokenCredentialsBuilder
    {
        if (empty($this->publicBearerTokenManager->getAccessToken())) {
            return null;
        }
        return PublicBearerTokenCredentialsBuilder::init($this->publicBearerTokenManager->getAccessToken());
    }

    public function getPublicBasicTokenCredentials(): PublicBasicTokenCredentials
    {
        return $this->publicBasicTokenManager;
    }

    public function getPublicBasicTokenCredentialsBuilder(): ?PublicBasicTokenCredentialsBuilder
    {
        if (empty($this->publicBasicTokenManager->getPublicBasicToken())) {
            return null;
        }
        return PublicBasicTokenCredentialsBuilder::init($this->publicBasicTokenManager->getPublicBasicToken());
    }

    public function getPrivateBasicTokenCredentials(): PrivateBasicTokenCredentials
    {
        return $this->privateBasicTokenManager;
    }

    public function getPrivateBasicTokenCredentialsBuilder(): ?PrivateBasicTokenCredentialsBuilder
    {
        if (empty($this->privateBasicTokenManager->getPublicBasicToken())) {
            return null;
        }
        return PrivateBasicTokenCredentialsBuilder::init($this->privateBasicTokenManager->getPublicBasicToken());
    }

    public function getClientAuthorizationTokenCredentials(): ClientAuthorizationTokenCredentials
    {
        return $this->clientAuthorizationTokenManager;
    }

    public function getClientAuthorizationTokenCredentialsBuilder(): ?ClientAuthorizationTokenCredentialsBuilder
    {
        if (
            empty($this->clientAuthorizationTokenManager->getOauthClientId()) &&
            empty($this->clientAuthorizationTokenManager->getOauthClientSecret())
        ) {
            return null;
        }
        return ClientAuthorizationTokenCredentialsBuilder::init(
            $this->clientAuthorizationTokenManager->getOauthClientId(),
            $this->clientAuthorizationTokenManager->getOauthClientSecret()
        )->oauthToken($this->clientAuthorizationTokenManager->getOauthToken());
    }

    public function getCustomerHeaderCredentials(): CustomerHeaderCredentials
    {
        return $this->customerHeaderManager;
    }

    public function getCustomerHeaderCredentialsBuilder(): ?CustomerHeaderCredentialsBuilder
    {
        if (empty($this->customerHeaderManager->getAuthorizationToken())) {
            return null;
        }
        return CustomerHeaderCredentialsBuilder::init($this->customerHeaderManager->getAuthorizationToken());
    }

    public function getLoggingConfigurationBuilder(): ?LoggingConfigurationBuilder
    {
        if (is_null($this->loggingConfigurationBuilder)) {
            return null;
        }
        $config = $this->loggingConfigurationBuilder->getConfiguration();
        return LoggingConfigurationBuilder::init()
            ->level($config['level'])
            ->logger($config['logger'])
            ->maskSensitiveHeaders($config['maskSensitiveHeaders'])
            ->requestConfiguration(RequestLoggingConfigurationBuilder::init()
                ->includeQueryInPath($config['requestConfiguration']['includeQueryInPath'])
                ->body($config['requestConfiguration']['body'])
                ->headers($config['requestConfiguration']['headers'])
                ->includeHeaders(...$config['requestConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['requestConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['requestConfiguration']['unmaskHeaders']))
            ->responseConfiguration(ResponseLoggingConfigurationBuilder::init()
                ->body($config['responseConfiguration']['body'])
                ->headers($config['responseConfiguration']['headers'])
                ->includeHeaders(...$config['responseConfiguration']['includeHeaders'])
                ->excludeHeaders(...$config['responseConfiguration']['excludeHeaders'])
                ->unmaskHeaders(...$config['responseConfiguration']['unmaskHeaders']));
    }

    /**
     * Get the proxy configuration builder
     */
    public function getProxyConfigurationBuilder(): ProxyConfigurationBuilder
    {
        return ProxyConfigurationBuilder::init($this->proxyConfiguration['address'])
            ->port($this->proxyConfiguration['port'])
            ->tunnel($this->proxyConfiguration['tunnel'])
            ->auth($this->proxyConfiguration['auth']['user'], $this->proxyConfiguration['auth']['pass'])
            ->authMethod($this->proxyConfiguration['auth']['method']);
    }

    /**
     * Get the client configuration as an associative array
     *
     * @see LoyaltyApIsClientBuilder::getConfiguration()
     */
    public function getConfiguration(): array
    {
        return $this->toBuilder()->getConfiguration();
    }

    /**
     * Clone this client and override given configuration options
     *
     * @see LoyaltyApIsClientBuilder::build()
     */
    public function withConfiguration(array $config): self
    {
        return new self(array_merge($this->config, $config));
    }

    /**
     * Get the base uri for a given server in the current environment.
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::SHELL): string
    {
        return $this->client->getGlobalRequest($server)->getQueryUrl();
    }

    /**
     * Returns Authorization Api
     */
    public function getAuthorizationApi(): AuthorizationApi
    {
        if ($this->authorization == null) {
            $this->authorization = new AuthorizationApi($this->client);
        }
        return $this->authorization;
    }

    /**
     * Returns Profile Management Api
     */
    public function getProfileManagementApi(): ProfileManagementApi
    {
        if ($this->profileManagement == null) {
            $this->profileManagement = new ProfileManagementApi($this->client);
        }
        return $this->profileManagement;
    }

    /**
     * Returns Offer Api
     */
    public function getOfferApi(): OfferApi
    {
        if ($this->offer == null) {
            $this->offer = new OfferApi($this->client);
        }
        return $this->offer;
    }

    /**
     * Returns Balances Api
     */
    public function getBalancesApi(): BalancesApi
    {
        if ($this->balances == null) {
            $this->balances = new BalancesApi($this->client);
        }
        return $this->balances;
    }

    /**
     * Returns Redemption Api
     */
    public function getRedemptionApi(): RedemptionApi
    {
        if ($this->redemption == null) {
            $this->redemption = new RedemptionApi($this->client);
        }
        return $this->redemption;
    }

    /**
     * Returns Transaction Api
     */
    public function getTransactionApi(): TransactionApi
    {
        if ($this->transaction == null) {
            $this->transaction = new TransactionApi($this->client);
        }
        return $this->transaction;
    }

    /**
     * Returns Oauth Authorization Api
     */
    public function getOauthAuthorizationApi(): OauthAuthorizationApi
    {
        if ($this->oauthAuthorization == null) {
            $this->oauthAuthorization = new OauthAuthorizationApi($this->client);
        }
        return $this->oauthAuthorization;
    }

    /**
     * A map of all base urls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::SIT => [
            Server::OAUTH_SERVER => 'https://api-test.shell.com',
            Server::SHELL => 'https://api-test.shell.com',
            Server::SHELL1 => 'https://api-test.shell.com/loyalty/v1',
            Server::SHELL2 => 'https://api-test.shell.com/loyalty'
        ],
        Environment::PRODUCTION => [
            Server::OAUTH_SERVER => 'https://api.shell.com',
            Server::SHELL => 'https://id.consumer.shell.com',
            Server::SHELL1 => 'https://api.shell.com/loyalty/v1',
            Server::SHELL2 => 'https://api.shell.com/loyalty'
        ],
        Environment::UAT => [
            Server::OAUTH_SERVER => 'https://api.shell.com',
            Server::SHELL => 'https://test.id.consumer.shell.com',
            Server::SHELL1 => 'https://api-uat.shell.com/loyalty/v1',
            Server::SHELL2 => 'https://api-uat.shell.com/loyalty'
        ]
    ];
}
