<?php

declare(strict_types=1);

/*
 * LoyaltyApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LoyaltyApIsLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const OAUTH_SERVER = 'OAuth Server';

    public const SHELL = 'Shell';

    public const SHELL1 = 'Shell1';

    public const SHELL2 = 'Shell2';
}
